const arrows = [
    { id: "left-arrow", dataTitle: "Left Arrow", text: "&#8592;" },
    { id: "up-arrow", dataTitle: "Up Arrow", text: "&#8593;" },
    { id: "right-arrow", dataTitle: "Right Arrow", text: "&#8594;" },
    { id: "down-arrow", dataTitle: "Down Arrow", text: "&#8595;" },
    { id: "left-right-arrow", dataTitle: "Left Right Arrow", text: "&#8596;" },
    { id: "up-down-arrow", dataTitle: "Up Down Arrow", text: "&#8597;" },
    { id: "north-west-arrow", dataTitle: "North West Arrow", text: "&#8598;" },
    { id: "north-east-arrow", dataTitle: "North East Arrow", text: "&#8599;" },
    { id: "south-east-arrow", dataTitle: "South East Arrow", text: "&#8600;" },
    { id: "south-west-arrow", dataTitle: "South West Arrow", text: "&#8601;" },
    { id: "left-arrow-with-stroke", dataTitle: "Left Arrow with Stroke", text: "&#8602;" },
    { id: "right-arrow-with-stroke", dataTitle: "Right Arrow with Stroke", text: "&#8603;" },
    { id: "left-wave-arrow", dataTitle: "Left Wave Arrow", text: "&#8604;" },
    { id: "right-wave-arrow", dataTitle: "Right Wave Arrow", text: "&#8605;" },
    { id: "left-two-headed-arrow", dataTitle: "Left Two Headed Arrow", text: "&#8606;" },
    { id: "up-two-headed-arrow", dataTitle: "Up Two Headed Arrow", text: "&#8607;" },
    { id: "right-two-headed-arrow", dataTitle: "Right Two Headed Arrow", text: "&#8608;" },
    { id: "down-two-headed-arrow", dataTitle: "Down Two Headed Arrow", text: "&#8609;" },
    { id: "left-arrow-with-tail", dataTitle: "Left Arrow with Tail", text: "&#8610;" },
    { id: "right-arrow-with-tail", dataTitle: "Right Arrow with Tail", text: "&#8611;" },
    { id: "left-arrow-from-bar", dataTitle: "Left Arrow from Bar", text: "&#8612;" },
    { id: "up-arrow-from-bar", dataTitle: "Up Arrow from Bar", text: "&#8613;" },
    { id: "right-arrow-from-bar", dataTitle: "Right Arrow from Bar", text: "&#8614;" },
    { id: "down-arrow-from-bar", dataTitle: "Down Arrow from Bar", text: "&#8615;" },
    { id: "up-down-arrow-with-base", dataTitle: "Up Down Arrow with Base", text: "&#8616;" },
    { id: "left-arrow-with-hook", dataTitle: "Left Arrow with Hook", text: "&#8617;" },
    { id: "right-arrow-with-hook", dataTitle: "Right Arrow with Hook", text: "&#8618;" },
    { id: "left-arrow-with-loop", dataTitle: "Left Arrow with Loop", text: "&#8619;" },
    { id: "right-arrow-with-loop", dataTitle: "Right Arrow with Loop", text: "&#8620;" },
    { id: "left-right-wave-arrow", dataTitle: "Left Right Wave Arrow", text: "&#8621;" },
    { id: "left-right-arrow-with-stroke", dataTitle: "Left Right Arrow with Stroke", text: "&#8622;" },
    { id: "downwards-zigzag-arrow", dataTitle: "Downwards Zigzag Arrow", text: "&#8623;" },
    { id: "upwards-arrow-with-tip-leftwards", dataTitle: "Upwards Arrow with Tip Leftwards", text: "&#8624;" },
    { id: "upwards-arrow-with-tip-rightwards", dataTitle: "Upwards Arrow with Tip Rightwards", text: "&#8625;" },
    { id: "downwards-arrow-with-tip-leftwards", dataTitle: "Downwards Arrow with Tip Leftwards", text: "&#8626;" },
    { id: "downwards-arrow-with-tip-rightwards", dataTitle: "Downwards Arrow with Tip Rightwards", text: "&#8627;" },
    { id: "right-arrow-with-corner-downwards", dataTitle: "Right Arrow with Corner Downwards", text: "&#8628;" },
    { id: "downwards-arrow-with-corner-leftwards", dataTitle: "Downwards Arrow with Corner Leftwards", text: "&#8629;" },
    { id: "anticlockwise-top-semicircle-arrow", dataTitle: "Anticlockwise Top Semicircle Arrow", text: "&#8630;" },
    { id: "clockwise-top-semicircle-arrow", dataTitle: "Clockwise Top Semicircle Arrow", text: "&#8631;" },
    { id: "north-west-arrow-to-long-bar", dataTitle: "North West Arrow to Long Bar", text: "&#8632;" },
    { id: "leftwards-arrow-to-bar-over-rightwards-arrow-to-bar", dataTitle: "Leftwards Arrow to Bar Over Rightwards Arrow to Bar", text: "&#8633;" },
    { id: "anticlockwise-open-circle-arrow", dataTitle: "Anticlockwise Open Circle Arrow", text: "&#8634;" },
    { id: "clockwise-open-circle-arrow", dataTitle: "Clockwise Open Circle Arrow", text: "&#8635;" },
    { id: "leftwards-harpoon-with-barb-upwards", dataTitle: "Leftwards Harpoon with Barb Upwards", text: "&#8636;" },
    { id: "leftwards-harpoon-with-barb-downwards", dataTitle: "Leftwards Harpoon with Barb Downwards", text: "&#8637;" },
    { id: "upwards-harpoon-with-barb-rightwards", dataTitle: "Upwards Harpoon with Barb Rightwards", text: "&#8638;" },
    { id: "upwards-harpoon-with-barb-leftwards", dataTitle: "Upwards Harpoon with Barb Leftwards", text: "&#8639;" },
    { id: "rightwards-harpoon-with-barb-upwards", dataTitle: "Rightwards Harpoon with Barb Upwards", text: "&#8640;" },
    { id: "rightwards-harpoon-with-barb-downwards", dataTitle: "Rightwards Harpoon with Barb Downwards", text: "&#8641;" },
    { id: "downwards-harpoon-with-barb-rightwards", dataTitle: "Downwards Harpoon with Barb Rightwards", text: "&#8642;" },
    { id: "downwards-harpoon-with-barb-leftwards", dataTitle: "Downwards Harpoon with Barb Leftwards", text: "&#8643;" },
    { id: "rightwards-arrow-over-leftwards-arrow", dataTitle: "Rightwards Arrow Over Leftwards Arrow", text: "&#8644;" },
    { id: "upwards-arrow-leftwards-of-downwards-arrow", dataTitle: "Upwards Arrow Leftwards of Downwards Arrow", text: "&#8645;" },
    { id: "leftwards-arrow-over-rightwards-arrow", dataTitle: "Leftwards Arrow Over Rightwards Arrow", text: "&#8646;" },
    { id: "leftwards-paired-arrows", dataTitle: "Leftwards Paired Arrows", text: "&#8647;" },
    { id: "upwards-paired-arrows", dataTitle: "Upwards Paired Arrows", text: "&#8648;" },
    { id: "rightwards-paired-arrows", dataTitle: "Rightwards Paired Arrows", text: "&#8649;" },
    { id: "downwards-paired-arrows", dataTitle: "Downwards Paired Arrows", text: "&#8650;" },
    { id: "leftwards-harpoon-over-rightwards-harpoon", dataTitle: "Leftwards Harpoon Over Rightwards Harpoon", text: "&#8651;" },
    { id: "rightwards-harpoon-over-leftwards-harpoon", dataTitle: "Rightwards Harpoon Over Leftwards Harpoon", text: "&#8652;" },
    { id: "leftwards-double-arrow-with-stroke", dataTitle: "Leftwards Double Arrow with Stroke", text: "&#8653;" },
    { id: "left-right-double-arrow-with-stroke", dataTitle: "Left Right Double Arrow with Stroke", text: "&#8654;" },
    { id: "rightwards-double-arrow-with-stroke", dataTitle: "Rightwards Double Arrow with Stroke", text: "&#8655;" },
    { id: "leftwards-double-arrow", dataTitle: "Leftwards Double Arrow", text: "&#8656;" },
    { id: "upwards-double-arrow", dataTitle: "Upwards Double Arrow", text: "&#8657;" },
    { id: "rightwards-double-arrow", dataTitle: "Rightwards Double Arrow", text: "&#8658;" },
    { id: "downwards-double-arrow", dataTitle: "Downwards Double Arrow", text: "&#8659;" },
    { id: "left-right-double-arrow", dataTitle: "Left Right Double Arrow", text: "&#8660;" },
    { id: "up-down-double-arrow", dataTitle: "Up Down Double Arrow", text: "&#8661;" },
    { id: "north-west-double-arrow", dataTitle: "North West Double Arrow", text: "&#8662;" },
    { id: "north-east-double-arrow", dataTitle: "North East Double Arrow", text: "&#8663;" },
    { id: "south-east-double-arrow", dataTitle: "South East Double Arrow", text: "&#8664;" },
    { id: "south-west-double-arrow", dataTitle: "South West Double Arrow", text: "&#8665;" },
    { id: "leftwards-triple-arrow", dataTitle: "Leftwards Triple Arrow", text: "&#8666;" },
    { id: "rightwards-triple-arrow", dataTitle: "Rightwards Triple Arrow", text: "&#8667;" },
    { id: "leftwards-squiggle-arrow", dataTitle: "Leftwards Squiggle Arrow", text: "&#8668;" },
    { id: "rightwards-squiggle-arrow", dataTitle: "Rightwards Squiggle Arrow", text: "&#8669;" },
    { id: "upwards-arrow-with-double-stroke", dataTitle: "Upwards Arrow with Double Stroke", text: "&#8670;" },
    { id: "downwards-arrow-with-double-stroke", dataTitle: "Downwards Arrow with Double Stroke", text: "&#8671;" },
    { id: "leftwards-dashed-arrow", dataTitle: "Leftwards Dashed Arrow", text: "&#8672;" },
    { id: "upwards-dashed-arrow", dataTitle: "Upwards Dashed Arrow", text: "&#8673;" },
    { id: "rightwards-dashed-arrow", dataTitle: "Rightwards Dashed Arrow", text: "&#8674;" },
    { id: "downwards-dashed-arrow", dataTitle: "Downwards Dashed Arrow", text: "&#8675;" },
    { id: "leftwards-arrow-to-bar", dataTitle: "Leftwards Arrow to Bar", text: "&#8676;" },
    { id: "rightwards-arrow-to-bar", dataTitle: "Rightwards Arrow to Bar", text: "&#8677;" },
    { id: "leftwards-white-arrow", dataTitle: "Leftwards White Arrow", text: "&#8678;" },
    { id: "upwards-white-arrow", dataTitle: "Upwards White Arrow", text: "&#8679;" },
    { id: "rightwards-white-arrow", dataTitle: "Rightwards White Arrow", text: "&#8680;" },
    { id: "downwards-white-arrow", dataTitle: "Downwards White Arrow", text: "&#8681;" },
    { id: "upwards-white-arrow-from-bar", dataTitle: "Upwards White Arrow from Bar", text: "&#8682;" },
    { id: "upwards-white-arrow-on-pedestal", dataTitle: "Upwards White Arrow on Pedestal", text: "&#8683;" },
    { id: "upwards-white-arrow-on-pedestal-with-horizontal-bar", dataTitle: "Upwards White Arrow on Pedestal with Horizontal Bar", text: "&#8684;" },
    { id: "upwards-white-arrow-on-pedestal-with-vertical-bar", dataTitle: "Upwards White Arrow on Pedestal with Vertical Bar", text: "&#8685;" },
    { id: "upwards-white-double-arrow", dataTitle: "Upwards White Double Arrow", text: "&#8686;" },
    { id: "upwards-white-double-arrow-on-pedestal", dataTitle: "Upwards White Double Arrow on Pedestal", text: "&#8687;" },
    { id: "rightwards-white-arrow-from-wall", dataTitle: "Rightwards White Arrow from Wall", text: "&#8688;" },
    { id: "north-west-arrow-to-corner", dataTitle: "North West Arrow to Corner", text: "&#8689;" },
    { id: "south-east-arrow-to-corner", dataTitle: "South East Arrow to Corner", text: "&#8690;" },
    { id: "up-down-white-arrow", dataTitle: "Up Down White Arrow", text: "&#8691;" },
    { id: "right-arrow-with-small-circle", dataTitle: "Right Arrow with Small Circle", text: "&#8692;" },
    { id: "downwards-arrow-leftwards-of-upwards-arrow", dataTitle: "Downwards Arrow Leftwards of Upwards Arrow", text: "&#8693;" },
    { id: "three-rightwards-arrows", dataTitle: "Three Rightwards Arrows", text: "&#8694;" },
    { id: "leftwards-arrow-with-vertical-stroke", dataTitle: "Leftwards Arrow with Vertical Stroke", text: "&#8695;" },
    { id: "rightwards-arrow-with-vertical-stroke", dataTitle: "Rightwards Arrow with Vertical Stroke", text: "&#8696;" },
    { id: "left-right-arrow-with-vertical-stroke", dataTitle: "Left Right Arrow with Vertical Stroke", text: "&#8697;" },
    { id: "leftwards-arrow-with-double-vertical-stroke", dataTitle: "Leftwards Arrow with Double Vertical Stroke", text: "&#8698;" },
    { id: "rightwards-arrow-with-double-vertical-stroke", dataTitle: "Rightwards Arrow with Double Vertical Stroke", text: "&#8699;" },
    { id: "left-right-arrow-with-double-vertical-stroke", dataTitle: "Left Right Arrow with Double Vertical Stroke", text: "&#8700;" },
    { id: "leftwards-open-headed-arrow", dataTitle: "Leftwards Open-Headed Arrow", text: "&#8701;" },
    { id: "rightwards-open-headed-arrow", dataTitle: "Rightwards Open-Headed Arrow", text: "&#8702;" },
    { id: "left-right-open-headed-arrow", dataTitle: "Left Right Open-Headed Arrow", text: "&#8703;" },
    { id: "up-quadruple-arrow", dataTitle: "Up Quadruple Arrow", text: "&#10224;" },
    { id: "down-quadruple-arrow", dataTitle: "Down Quadruple Arrow", text: "&#10225;" },
    { id: "anticlockwise-gapped-circle-arrow", dataTitle: "Anticlockwise Gapped Circle Arrow", text: "&#10226;" },
    { id: "clockwise-gapped-circle-arrow", dataTitle: "Clockwise Gapped Circle Arrow", text: "&#10227;" },
    { id: "right-arrow-with-circled-plus", dataTitle: "Right Arrow with Circled Plus", text: "&#10228;" },
    { id: "long-leftwards-arrow", dataTitle: "Long Leftwards Arrow", text: "&#10229;" },
    { id: "long-rightwards-arrow", dataTitle: "Long Rightwards Arrow", text: "&#10230;" },
    { id: "long-left-right-arrow", dataTitle: "Long Left Right Arrow", text: "&#10231;" },
    { id: "long-leftwards-double-arrow", dataTitle: "Long Leftwards Double Arrow", text: "&#10232;" },
    { id: "long-rightwards-double-arrow", dataTitle: "Long Rightwards Double Arrow", text: "&#10233;" },
    { id: "long-left-right-double-arrow", dataTitle: "Long Left Right Double Arrow", text: "&#10234;" },
    { id: "long-leftwards-arrow-from-bar", dataTitle: "Long Leftwards Arrow from Bar", text: "&#10236;" },
    { id: "long-rightwards-arrow-from-bar", dataTitle: "Long Rightwards Arrow from Bar", text: "&#10237;" },
    { id: "long-leftwards-double-arrow-from-bar", dataTitle: "Long Leftwards Double Arrow from Bar", text: "&#10238;" },
    { id: "long-right-squiggle-arrow", dataTitle: "Long Right-squiggle-arrow", text: "&#10239;" },
    { id: "heavy-wide-headed-rightwards-arrow", dataTitle: "Heavy Wide-Headed Rightwards Arrow", text: "&#10132;" },
    { id: "heavy-round-tipped-rightwards-arrow", dataTitle: "Heavy Round-Tipped Rightwards Arrow", text: "&#10140;" },
    { id: "triangle-headed-rightwards-arrow", dataTitle: "Triangle-Headed Rightwards Arrow", text: "&#10142;" },
    { id: "white-triangle-headed-rightwards-arrow", dataTitle: "White Triangle-Headed Rightwards Arrow", text: "&#10143;" },
    { id: "heavy-triangle-headed-rightwards-arrow", dataTitle: "Heavy Triangle-Headed Rightwards Arrow", text: "&#10144;" },
    { id: "white-triangle-headed-rightwards-arrow-from-bar", dataTitle: "White Triangle-Headed Rightwards Arrow from Bar", text: "&#10145;" },
    { id: "three-d-top-lighted-righ-arrowhead", dataTitle: "Three-D Top-Lighted Right Arrowhead", text: "&#10146;" },
    { id: "three-d-bottom-lighted-righ-arrowhead", dataTitle: "Three-D Bottom-Lighted Right Arrowhead", text: "&#10147;" },
    { id: "black-right-arrowhead", dataTitle: "Black Right Arrowhead", text: "&#10148;" },
    { id: "heavy-black-curved-down-right-arrow", dataTitle: "heavy-black-curved-down-right-arrow", text: "&#10149;" },
    { id: "heavy-black-curved-up-right-arrow", dataTitle: "Heavy Black-Curved Up Right Arrow", text: "&#10150;" },
    { id: "squat-black-right-arrow", dataTitle: "Squat Black Right Arrow", text: "&#10151;" },
    { id: "rightwards-two-headed-triangle-arrow", dataTitle: "Rightwards Two-Headed Triangle Arrow", text: "&#10152;" },
    { id: "lower-right-semicircular-clockwise-arrow", dataTitle: "Lower Right Semicircular Clockwise Arrow", text: "&#10558;" },
    { id: "lower-left-semicircular-anticlockwise-arrow", dataTitle: "Lower Left Semicircular Anticlockwise Arrow", text: "&#10559;" },
    { id: "anticlockwise-closed-circle-arrow", dataTitle: "Anticlockwise Closed Circle Arrow", text: "&#10560;" }
    
]
export default arrows;
