const smileys = [
    { text: "&#x1F600;", id: "grinning-face", dataTitle: "Grinning Face" },
    { text: "&#x1F601;", id: "grinning-face-with-smiling-eyes", dataTitle: "grinning face with smiling eyes" },
    { text: "&#x1F602;", id: "face-with-tears-of-joy", dataTitle: "Face with tears of joy" },
    { text: "&#x1F603;", id: "smiling-face-with-open-mouth", dataTitle: "Smiling face with open mouth" },
    { text: "&#x1F604;", id: "smiling-face-with-open-mouth-and-smiling-eyes", dataTitle: "Smiling face with open mouth and smiling eyes" },
    { text: "&#x1F605;", id: "smiling-face-with-open-mouth-and-cold-sweat", dataTitle: "Smiling face with open mouth and cold sweat" },
    { text: "&#x1F606;", id: "smiling-face-with-open-mouth-and-tightly-closed-eyes", dataTitle: "Smiling face with open mouth and tightly-closed eyes" },
    { text: "&#x1F607;", id: "smiling-face-with-halo", dataTitle: "Smiling face with halo" },
    { text: "&#x1F608;", id: "smiling-face-with-horns", dataTitle: "Smiling face with horns" },
    { text: "&#x1F609;", id: "winking-face", dataTitle: "winking face" },
    { text: "&#x1F60A;", id: "smiling-face-with-smiling-eyes", dataTitle: "Smiling face with smiling eyes" },
    { text: "&#x1F60B;", id: "face-savouring-delicious-food", dataTitle: "Face savouring delicious food" },
    { text: "&#x1F60C;", id: "relieved-face", dataTitle: "relieved face" },
    { text: "&#x1F60D;", id: "smiling-face-with-heart-shaped-eyes", dataTitle: "Smiling face with heart-shaped eyes" },
    { text: "&#x1F60E;", id: "smiling-face-with-sunglasses", dataTitle: "Smiling face with sunglasses" },
    { text: "&#x1F60F;", id: "smirking-face", dataTitle: "Smirking face" },
    { text: "&#x1F610;", id: "neutral-face", dataTitle: "neutral face" },
    { text: "&#x1F611;", id: "expressionless-face", dataTitle: "expressionless face" },
    { text: "&#x1F612;", id: "unamused-face", dataTitle: "unamused face" },
    { text: "&#x1F613;", id: "face-with-cold-sweat", dataTitle: "Face with cold sweat" },
    { text: "&#x1F614;", id: "pensive-face", dataTitle: "Pensive face" },
    { text: "&#x1F615;", id: "confused-face", dataTitle: "Confused face" },
    { text: "&#x1F616;", id: "confounded-face", dataTitle: "Confounded face" },
    { text: "&#x1F617;", id: "kissing-face", dataTitle: "kissing face" },
    { text: "&#x1F618;", id: "face-throwing-kiss", dataTitle: "Face throwing kiss" },
    { text: "&#x1F619;", id: "kissing-face-with-smiling-eyes", dataTitle: "kissing face with smiling eyes" },
    { text: "&#x1F61A;", id: "kissing-face-with-closed-eyes", dataTitle: "kissing face with closed eyes" },
    { text: "&#x1F61B;", id: "face-with-stuck-out-tongue", dataTitle: "Face with stuck-out tongue" },
    { text: "&#x1F61C;", id: "face-with-stuck-out-tongue-and-winking-eye", dataTitle: "Face with stuck-out tongue and winking eye" },
    { text: "&#x1F61D;", id: "face-with-stuck-out-tongue-and-tightly-closed-eyes", dataTitle: "Face with stuck-out tongue and tightly-closed eyes" },
    { text: "&#x1F61E;", id: "disappointed-face", dataTitle: "Disappointed face" },
    { text: "&#x1F61F;", id: "worried-face", dataTitle: "worried face" },
    { text: "&#x1F620;", id: "angry-face", dataTitle: "Angry face" },
    { text: "&#x1F621;", id: "pouting-face", dataTitle: "Pouting face" },
    { text: "&#x1F622;", id: "crying-face", dataTitle: "Crying face" },
    { text: "&#x1F623;", id: "persevering-face", dataTitle: "Persevering face" },
    { text: "&#x1F624;", id: "face-with-look-of-triumph", dataTitle: "Face with look of triumph" },
    { text: "&#x1F625;", id: "disappointed-but-relieved-face", dataTitle: "Disappointed but relieved face" },
    { text: "&#x1F626;", id: "frowning-face-with-open-mouth", dataTitle: "Frowning face with open mouth" },
    { text: "&#x1F627;", id: "anguished-face", dataTitle: "Anguished face" },
    { text: "&#x1F628;", id: "fearful-face", dataTitle: "Fearful face" },
    { text: "&#x1F629;", id: "weary-face", dataTitle: "weary face" },
    { text: "&#x1F62A;", id: "sleepy-face", dataTitle: "Sleepy face" },
    { text: "&#x1F62B;", id: "tired-face", dataTitle: "Tired face" },
    { text: "&#x1F62C;", id: "grimacing-face", dataTitle: "grimacing face" },
    { text: "&#x1F62D;", id: "loudly-crying-face", dataTitle: "Loudly crying face" },
    { text: "&#x1F62E;", id: "face-with-open-mouth", dataTitle: "Face with open mouth" },
    { text: "&#x1F62F;", id: "hushed-face", dataTitle: "Hushed face" },
    { text: "&#x1F630;", id: "face-with-open-mouth-and-cold-sweat", dataTitle: "Face with open mouth and cold sweat" },
    { text: "&#x1F631;", id: "face-screaming-in-fear", dataTitle: "Face screaming in fear" },
    { text: "&#x1F632;", id: "astonished-face", dataTitle: "Astonished face" },
    { text: "&#x1F633;", id: "flushed-face", dataTitle: "Flushed face" },
    { text: "&#x1F634;", id: "sleeping-face", dataTitle: "Sleeping face" },
    { text: "&#x1F635;", id: "dizzy-face", dataTitle: "Dizzy face" },
    { text: "&#x1F636;", id: "face-without-mouth", dataTitle: "Face without mouth" },
    { text: "&#x1F637;", id: "face-with-medical-mask", dataTitle: "Face with medical mask" },
    { text: "&#x1F641;", id: "slightly-frowning-face", dataTitle: "Slightly frowning face" },
    { text: "&#x1F642;", id: "slightly-smiling-face", dataTitle: "Slightly smiling face" },
    { text: "&#x1F643;", id: "upside-down-face", dataTitle: "upside-down face" },
    { text: "&#x1F644;", id: "face-with-rolling-eyes", dataTitle: "Face with rolling eyes" },
    { text: "&#x1F910;", id: "zipper-mouth-face", dataTitle: "zipper-mouth face" },
    { text: "&#x1F911;", id: "money-mouth-face", dataTitle: "Money-mouth face" },
    { text: "&#x1F912;", id: "face-with-thermometer", dataTitle: "Face with thermometer" },
    { text: "&#x1F913;", id: "nerd-face", dataTitle: "nerd face" },
    { text: "&#x1F914;", id: "thinking-face", dataTitle: "Thinking face" },
    { text: "&#x1F915;", id: "face-with-head-bandage", dataTitle: "Face with head-bandage" },
    { text: "&#x1f920;", id: "face-with-cowboy-hat", dataTitle: "Face with cowboy hat" },
    { text: "&#x1f921;", id: "clown-face", dataTitle: "Clown face" },
    { text: "&#x1f922;", id: "nauseated-face", dataTitle: "nauseated face" },
    { text: "&#x1f923;", id: "rolling-on-the-floor-laughing", dataTitle: "rolling on the floor laughing" },
    { text: "&#x1f924;", id: "drooling-face", dataTitle: "Drooling face" },
    { text: "&#x1f925;", id: "lying-face", dataTitle: "Lying face" },
    { text: "&#x1f927;", id: "shushing-face", dataTitle: "Shushing face" },
    { text: "&#x1f928;", id: "face-with-hand-over-mouth", dataTitle: "Face with hand over mouth" },
    { text: "&#x1f929;", id: "grinning-face-with-star-eyes", dataTitle: "grinning face with star eyes" },
    { text: "&#x1f92a;", id: "grinning-face-with-one-large-and-one-small-eye", dataTitle: "grinning face with one large and one small eye" },
    { text: "&#x1f92b;", id: "face-with-finger-covering-closed-lips", dataTitle: "Face with finger covering closed lips" },
    { text: "&#x1f92c;", id: "serious-face-with-symbols-covering-mouth", dataTitle: "Serious face with symbols covering mouth" },
    { text: "&#x1f92d;", id: "smiling-face-with-smiling-eyes-and-hand-covering-mouth", dataTitle: "Smiling face with smiling eyes and hand covering mouth" },
    { text: "&#x1f92e;", id: "face-with-open-mouth-vomiting", dataTitle: "Face with open mouth vomiting" },
    { text: "&#x1f92f;", id: "shocked-face-with-exploding-head", dataTitle: "Shocked face with exploding head" },
    { text: "&#x1f9d0;", id: "face-with-monocle", dataTitle: "Face with monocle" },
    { text: "&#x1F4A9;", id: "pile-of-poo", dataTitle: "Pile of poo" },
    { text: "&#x1F638;", id: "grinning-cat-face-with-smiling-eyes", dataTitle: "grinning cat face with smiling eyes" },
    { text: "&#x1F639;", id: "cat-face-with-tears-of-joy", dataTitle: "cat face with tears of joy" },
    { text: "&#x1F63A;", id: "smiling-cat-face-with-open-mouth", dataTitle: "smiling cat face with open mouth" },
    { text: "&#x1F63B;", id: "smiling-cat-face-with-heart-shaped-eyes", dataTitle: "smiling cat face with heart-shaped eyes" },
    { text: "&#x1F63C;", id: "cat-face-with-wry-smile", dataTitle: "cat face with wry smile" },
    { text: "&#x1F63D;", id: "kissing-cat-face-with-closed-eyes", dataTitle: "kissing cat face with closed eyes" },
    { text: "&#x1F63E;", id: "pouting-cat-face", dataTitle: "pouting cat face" },
    { text: "&#x1F63F;", id: "crying-cat-face", dataTitle: "crying cat face" },
    { text: "&#x1F640;", id: "weary-cat-face", dataTitle: "weary cat face" },
    { text: "&#x1F648;", id: "see-no-evil-monkey", dataTitle: "see-no-evil monkey" },
    { text: "&#x1F649;", id: "hear-no-evil-monkey", dataTitle: "hear-no-evil monkey" },
    { text: "&#x1F64A;", id: "speak-no-evil-monkey", dataTitle: "speak-no-evil monkey" },
];
const people = [
    
    /* hands */
    { text: "&#x261d;", id: "white-up-pointing-index", dataTitle: "white up pointing index" },
    { text: "&#x270a;", id: "raised-fist", dataTitle: "raised fist" },
    { text: "&#x270b;", id: "raised-hand", dataTitle: "raised hand" },
    { text: "&#x1F590;", id: "raised-hand-with-fingers-splayed", dataTitle: "raised hand with fingers splayed" },
    { text: "&#x270c;", id: "victory-hand", dataTitle: "victory hand" },
    { text: "&#x270d;", id: "writing-hand", dataTitle: "writing hand" },
    { text: "&#x1f44a;", id: "fisted-hand-sign", dataTitle: "Fisted hand sign" },
    { text: "&#x1f44b;", id: "waving-hand-sign", dataTitle: "waving hand sign" },
    { text: "&#x1f44c;", id: "ok-hand-sign", dataTitle: "ok hand sign" },
    { text: "&#x1f44d;", id: "thumbs-up-sign", dataTitle: "Thumbs up sign" },
    { text: "&#x1f44e;", id: "thumbs-down-sign", dataTitle: "Thumbs down sign" },
    { text: "&#x1f44f;", id: "clapping-hands-sign", dataTitle: "Clapping hands sign" },
    { text: "&#x1f450;", id: "open-hands-sign", dataTitle: "open hands sign" },
    { text: "&#x1f64c;", id: "person-raising-both-hands-in-celebration", dataTitle: "Person raising both hands in celebration" },
    { text: "&#x1f64f;", id: "person-with-folded-hands", dataTitle: "Person with folded hands" },
    { text: "&#x1f91a;", id: "raised-back-of-hand", dataTitle: "raised back of hand" },
    { text: "&#x1f91b;", id: "left-facing-fist", dataTitle: "Left-facing fist" },
    { text: "&#x1f91c;", id: "right-facing-fist", dataTitle: "right-facing fist" },
    { text: "&#x1f91e;", id: "hand-with-index-and-middle-fingers-crossed", dataTitle: "Hand with index and middle fingers crossed" },
    { text: "&#x1f91f;", id: "i-love-you-hand-sign", dataTitle: "I love you hand sign" },
    { text: "&#x1f918;", id: "sign-of-the-horns", dataTitle: "Sign of the horns" },
    { text: "&#x1f919;", id: "call-me-hand", dataTitle: "Call me hand" },
    { text: "&#x1f448;", id: "white-left-pointing-backhand-index", dataTitle: "white left pointing backhand index" },
    { text: "&#x1f449;", id: "white-right-pointing-backhand-index", dataTitle: "white right pointing backhand index" },
    { text: "&#x1f446;", id: "white-up-pointing-backhand-index", dataTitle: "white up pointing backhand index" },
    { text: "&#x1f447;", id: "white-down-pointing-backhand-index", dataTitle: "white down pointing backhand index" },
    { text: "&#x1f595;", id: "reversed-hand-with-middle-finger-extended", dataTitle: "reversed hand with middle finger extended" },
    { text: "&#x1F596;", id: "raised-hand-with-part-between-middle-and-ring-fingers", dataTitle: "raised hand with part between middle and ring fingers" },
    { text: "&#x1F932;", id: "palms-up-together", dataTitle: "Palms up together" },
    { text: "&#x1F4AA;", id: "flexed-biceps", dataTitle: "Flexed biceps" },
    { text: "&#x1F91D;", id: "handshake", dataTitle: "Handshake" },
    { text: "&#x1F485;", id: "nail-polish", dataTitle: "nail polish" },
    { text: "&#x1F933;", id: "selfie", dataTitle: "Selfie" },

    /* fantasy people */
    
    { text: "&#x1F9D9;", id: "mage", dataTitle: "Mage" },
    { text: "&#x1F9DA;", id: "fairy", dataTitle: "Fairy" },
    { text: "&#x1F9DB;", id: "vampire", dataTitle: "Vampire" },
    { text: "&#x1F9DC;", id: "merperson", dataTitle: "Merperson" },
    { text: "&#x1F9DD;", id: "elf", dataTitle: "Elf" },
    { text: "&#x1F9DE;", id: "genie", dataTitle: "Genie" },
    { text: "&#x1F9DF;", id: "zombie", dataTitle: "Zombie" },
    { text: "&#x1F916;", id: "robot-face", dataTitle: "robot face" },
    { text: "&#x1F9D8;", id: "person-in-lotus-position", dataTitle: "Person in lotus position" },
    { text: "&#x1F9D5;", id: "person-with-headscarf", dataTitle: "Person with headscarf" },
    { text: "&#x1F931;", id: "breast-feeding", dataTitle: "Breast-feeding" },
    { text: "&#x1F930;", id: "pregnant-woman", dataTitle: "Pregnant-woman" },
    { text: "&#x1F466;", id: "boy", dataTitle: "Boy" },
    { text: "&#x1F467;", id: "girl", dataTitle: "Girl" },
    { text: "&#x1F468;", id: "man", dataTitle: "Man" },
    { text: "&#x1F469;", id: "woman", dataTitle: "Woman" },
    { text: "&#x1F476;", id: "baby", dataTitle: "Baby" },
    { text: "&#x1F475;", id: "older-woman", dataTitle: "Older Woman" },
    { text: "&#x1F474;", id: "older-man", titl: "Older Man" },
    { text: "&#x1F479;", id: "japanese-ogre", dataTitle: "Japanese Ogre" },
    { text: "&#x1F47A;", id: "japanese-goblin", dataTitle: "Japanese Goblin" },
    { text: "&#x1F480;", id: "skull", dataTitle: "Skull" },
    { text: "&#x1F47B;", id: "ghost", dataTitle: "Ghost" },
    { text: "&#x1F47D;", id: "extraterrestrial-alien", dataTitle: "Extraterrestrial Alien" },
    { text: "&#x1F47E;", id: "alien-monster", dataTitle: "Alien Monster / Space Invader" },
    { text: "&#x1F385;", id: "father-christmas", dataTitle: "Father Christmas" },

        // Creatures
        {
          text: "&#x1F608;",
          id: "smiling_imp",
          dataTitle: "Smiling Imp"
        },
        {
          text: "&#x1F47F;",
          id: "imp",
          dataTitle: "Imp"
        },
        {
          text: "&#x1F480;",
          id: "skull",
          dataTitle: "Skull"
        },
        {
          text: "&#x1F4A9;",
          id: "poop_face",
          dataTitle: "poop face"
        },
        {
          text: "&#x1F921;",
          id: "clown_face",
          dataTitle: "Clown Face"
        },

];

const animals_nature = [
    /* animals */
    { text: "&#x1F400;", id: "rat", dataTitle: "Rat" },
    { text: "&#x1F401;", id: "mouse", dataTitle: "Mouse" },
    { text: "&#x1F402;", id: "ox", dataTitle: "Ox" },
    { text: "&#x1F403;", id: "water-buffalo", dataTitle: "Water Buffalo" },
    { text: "&#x1F404;", id: "cow", dataTitle: "Cow" },
    { text: "&#x1F405;", id: "tiger", dataTitle: "Tiger" },
    { text: "&#x1F406;", id: "leopard", dataTitle: "Leopard" },
    { text: "&#x1F407;", id: "rabbit", dataTitle: "Rabbit" },
    { text: "&#x1F408;", id: "cat", dataTitle: "Cat" },
    { text: "&#x1F409;", id: "dragon", dataTitle: "Dragon" },
    { text: "&#x1F40A;", id: "crocodile", dataTitle: "Crocodile" },
    { text: "&#x1F40B;", id: "whale", dataTitle: "Whale" },
    { text: "&#x1F40C;", id: "snail", dataTitle: "Snail" },
    { text: "&#x1F40D;", id: "snake", dataTitle: "Snake" },
    { text: "&#x1F40E;", id: "horse", dataTitle: "Horse" },
    { text: "&#x1F40F;", id: "ram", dataTitle: "Ram" },
    { text: "&#x1F410;", id: "goat", dataTitle: "Goat" },
    { text: "&#x1F411;", id: "sheep", dataTitle: "Sheep" },
    { text: "&#x1F412;", id: "monkey", dataTitle: "Monkey" },
    { text: "&#x1F413;", id: "rooster", dataTitle: "Rooster" },
    { text: "&#x1F414;", id: "chicken", dataTitle: "Chicken" },
    { text: "&#x1F415;", id: "dog", dataTitle: "Dog" },
    { text: "&#x1F416;", id: "pig", dataTitle: "Pig" },
    { text: "&#x1F417;", id: "boar", dataTitle: "Boar" },
    { text: "&#x1F418;", id: "elephant", dataTitle: "Elephant" },
    { text: "&#x1F419;", id: "octopus", dataTitle: "Octopus" },
    { text: "&#x1F41A;", id: "spiral-shell", dataTitle: "Spiral Shell" },
    { text: "&#x1F41B;", id: "bug", dataTitle: "Bug" },
    { text: "&#x1F41C;", id: "ant", dataTitle: "Ant" },
    { text: "&#x1F41D;", id: "honeybee", dataTitle: "Honeybee" },
    { text: "&#x1F41E;", id: "lady-beetle", dataTitle: "Lady Beetle" },
    { text: "&#x1F41F;", id: "fish", dataTitle: "Fish" },
    { text: "&#x1F420;", id: "tropical-fish", dataTitle: "Tropical Fish" },
    { text: "&#x1F421;", id: "blowfish", dataTitle: "Blowfish" },
    { text: "&#x1F422;", id: "turtle", dataTitle: "Turtle" },
    { text: "&#x1F423;", id: "hatching-chick", dataTitle: "Hatching Chick" },
    { text: "&#x1F424;", id: "baby-chick", dataTitle: "Baby Chick" },
    { text: "&#x1F425;", id: "front-facing-baby-chick", dataTitle: "Front-Facing Baby Chick" },
    { text: "&#x1F426;", id: "bird", dataTitle: "Bird" },
    { text: "&#x1F427;", id: "penguin", dataTitle: "Penguin" },
    { text: "&#x1F428;", id: "koala", dataTitle: "Koala" },
    { text: "&#x1F429;", id: "poodle", dataTitle: "Poodle" },
    { text: "&#x1F42A;", id: "dromedary-camel", dataTitle: "Dromedary Camel" },
    { text: "&#x1F42B;", id: "bactrian-camel", dataTitle: "Bactrian Camel" },
    { text: "&#x1F42C;", id: "dolphin", dataTitle: "Dolphin" },
    { text: "&#x1F42D;", id: "mouse-face", dataTitle: "Mouse Face" },
    { text: "&#x1F42E;", id: "cow-face", dataTitle: "Cow Face" },
    { text: "&#x1F42F;", id: "tiger-face", dataTitle: "Tiger Face" },
    { text: "&#x1F430;", id: "rabbit-face", dataTitle: "Rabbit Face" },
    { text: "&#x1F431;", id: "cat-face", dataTitle: "Cat Face" },
    { text: "&#x1F432;", id: "dragon-face", dataTitle: "Dragon Face" },
    { text: "&#x1F433;", id: "spouting-whale", dataTitle: "Spouting Whale" },
    { text: "&#x1F434;", id: "horse-face", dataTitle: "Horse Face" },
    { text: "&#x1F435;", id: "monkey-face", dataTitle: "Monkey Face" },
    { text: "&#x1F436;", id: "dog-face", dataTitle: "Dog Face" },
    { text: "&#x1F437;", id: "pig-face", dataTitle: "Pig Face" },
    { text: "&#x1F438;", id: "frog-face", dataTitle: "Frog Face" },
    { text: "&#x1F439;", id: "hamster-face", dataTitle: "Hamster Face" },
    { text: "&#x1F43A;", id: "wolf-face", dataTitle: "Wolf Face" },
    { text: "&#x1F43B;", id: "bear-face", dataTitle: "Bear Face" },
    { text: "&#x1F43C;", id: "panda-face", dataTitle: "Panda Face" },
    { text: "&#x1F43D;", id: "pig-nose", dataTitle: "Pig Nose" },
    { text: "&#x1F43E;", id: "paw-prints", dataTitle: "Paw Prints" },

    /* plants */
    { text: "&#x1F330;", id: "chestnut", dataTitle: "Chestnut" },
    { text: "&#x1F331;", id: "seedling", dataTitle: "Seedling" },
    { text: "&#x1F332;", id: "evergreen-tree", dataTitle: "Evergreen Tree" },
    { text: "&#x1F333;", id: "deciduous-tree", dataTitle: "Deciduous Tree" },
    { text: "&#x1F334;", id: "palm-tree", dataTitle: "Palm Tree" },
    { text: "&#x1F335;", id: "cactus", dataTitle: "Cactus" },
    { text: "&#x1F336;", id: "hot-pepper", dataTitle: "Hot Pepper" },
    { text: "&#x1F337;", id: "tulip", dataTitle: "Tulip" },
    { text: "&#x1F338;", id: "cherry-blossom", dataTitle: "Cherry Blossom" },
    { text: "&#x1F339;", id: "rose", dataTitle: "Rose" },
    { text: "&#x1F33A;", id: "hibiscus", dataTitle: "Hibiscus" },
    { text: "&#x1F33B;", id: "sunflower", dataTitle: "Sunflower" },
    { text: "&#x1F33C;", id: "blossom", dataTitle: "Blossom" },
    { text: "&#x1F33D;", id: "ear-of-maize", dataTitle: "Ear of Maize" },
    { text: "&#x1F33E;", id: "ear-of-rice", dataTitle: "Ear of Rice" },
    { text: "&#x1F33F;", id: "herb", dataTitle: "Herb" },
    { text: "&#x1F340;", id: "four-leaf-clover", dataTitle: "Four Leaf Clover" },
    { text: "&#x1F341;", id: "maple-leaf", dataTitle: "Maple Leaf" },
    { text: "&#x1F342;", id: "fallen-leaf", dataTitle: "Fallen Leaf" },
    { text: "&#x1F343;", id: "leaf-fluttering-in-wind", dataTitle: "Leaf Fluttering in Wind" },

    /* moon & sun */
    { text: "&#x1F31F;", id: "glowing-star", dataTitle: "Glowing Star" },
    { text: "&#x1F320;", id: "shooting-star", dataTitle: "Shooting Star" },
    { text: "&#x1F311;", id: "new-moon-symbol", dataTitle: "New Moon Symbol" },
    { text: "&#x1F312;", id: "waxing-crescent-moon-symbol", dataTitle: "Waxing Crescent Moon Symbol" },
    { text: "&#x1F313;", id: "first-quarter-moon-symbol", dataTitle: "First Quarter Moon Symbol" },
    { text: "&#x1F314;", id: "waxing-gibbous-moon-symbol", dataTitle: "Waxing Gibbous Moon Symbol" },
    { text: "&#x1F315;", id: "full-moon-symbol", dataTitle: "Full Moon Symbol" },
    { text: "&#x1F316;", id: "waning-gibbous-moon-symbol", dataTitle: "Waning Gibbous Moon Symbol" },
    { text: "&#x1F317;", id: "last-quarter-moon-symbol", dataTitle: "Last Quarter Moon Symbol" },
    { text: "&#x1F318;", id: "waning-crescent-moon-symbol", dataTitle: "Waning Crescent Moon Symbol" },
    { text: "&#x1F319;", id: "crescent-moon", dataTitle: "Crescent Moon" },
    { text: "&#x1F31A;", id: "new-moon-with-face", dataTitle: "New Moon with Face" },
    { text: "&#x1F31B;", id: "first-quarter-moon-with-face", dataTitle: "First Quarter Moon with Face" },
    { text: "&#x1F31C;", id: "last-quarter-moon-with-face", dataTitle: "Last Quarter Moon with Face" },
    { text: "&#x1F31D;", id: "full-moon-with-face", dataTitle: "Full Moon with Face" },
    { text: "&#x1F31E;", id: "sun-with-face", dataTitle: "Sun with Face" },
    { text: "&#x1FA90;", id: "saturn", dataTitle: "Saturn" },

    /* weather */
    { text: "&#x26C5;", id: "sun-behind-cloud", dataTitle: "Sun behind cloud" },
    { text: "&#x1f302;", id: "closed-umbrella", dataTitle: "Closed umbrella" },
    { text: "&#x1f303;", id: "night-with-stars", dataTitle: "night with stars" },
    { text: "&#x1f301;", id: "foggy", dataTitle: "Foggy" },
    { text: "&#x1f304;", id: "sunrise-over-mountains", dataTitle: "Sunrise over mountains" },
    { text: "&#x1f305;", id: "sunrise", dataTitle: "Sunrise" },
    { text: "&#x1f306;", id: "cityscape-at-dusk", dataTitle: "Cityscape at dusk" },
    { text: "&#x1f307;", id: "sunset-over-buildings", dataTitle: "Sunset over buildings" },
    { text: "&#127754;", id: "water-wave", dataTitle: "Water wave" },
    { text: "&#x2600;", id: "black-sun-with-rays", dataTitle: "Black sun with rays" },
    { text: "&#x2601;", id: "cloud", dataTitle: "Cloud" },
    { text: "&#x26C4;", id: "snowman", dataTitle: "Snowman" },

    /* new weather */
    { text: "&#x1F324;", id: "sun-behind-small-cloud", dataTitle: "Sun Behind Small Cloud" },
    { text: "&#x1F325;", id: "sun-behind-large-cloud", dataTitle: "Sun Behind Large Cloud" },
    { text: "&#x1F326;", id: "sun-behind-rain-cloud", dataTitle: "Sun Behind Rain Cloud" },
    { text: "&#x1F327;", id: "cloud-with-rain", dataTitle: "Cloud with Rain" },
    { text: "&#x1F328;", id: "cloud-with-snow", dataTitle: "Cloud with Snow" },
    { text: "&#x26c8", id: "cloud-with-lightning-and-rain", dataTitle: "Cloud with Lightning and Rain" },
    { text: "&#x1F329;", id: "cloud-with-lighting", dataTitle: "Cloud with Lightning" },
    { text: "&#x1F32A;", id: "Tornado", dataTitle: "Tornado" },
    { text: "&#x1F32B;", id: "fog", dataTitle: "Fog" },
    { text: "&#x1F32C;", id: "wind-face", dataTitle: "Wind Face" },
    { text: "&#x1F300;", id: "cyclone", dataTitle: "Cyclone" },
    { text: "&#x1F308;", id: "rainbow", dataTitle: "Rainbow" },
    { text: "&#x2602;", id: "umbrella", dataTitle: "Umbrella" },
    { text: "&#x2614;", id: "umbrella-with-rain-drops", dataTitle: "Umbrella with Rain Drops" },
    { text: "&#x2744;", id: "snowflake", dataTitle: "Snowflake" },
    { text: "&#x2604;", id: "comet", dataTitle: "Comet" },
];

const food_drinks = [
    /* food & drinks*/
    { text: "&#x1F32D;", id: "hot-dog", dataTitle: "Hot Dog" },
    { text: "&#x1F32E;", id: "taco", dataTitle: "Taco" },
    { text: "&#x1F32F;", id: "burrito", dataTitle: "Burrito" },
    { text: "&#x1F344;", id: "mushroom", dataTitle: "Mushroom" },
    { text: "&#x1F345;", id: "tomato", dataTitle: "Tomato" },
    { text: "&#x1F346;", id: "aubergine", dataTitle: "Aubergine" },
    { text: "&#x1F347;", id: "grapes", dataTitle: "Grapes" },
    { text: "&#x1F348;", id: "melon", dataTitle: "Melon" },
    { text: "&#x1F349;", id: "watermelon", dataTitle: "Watermelon" },
    { text: "&#x1F34A;", id: "tangerine", dataTitle: "Tangerine" },
    { text: "&#x1F34B;", id: "lemon", dataTitle: "Lemon" },
    { text: "&#x1F34C;", id: "banana", dataTitle: "Banana" },
    { text: "&#x1F34D;", id: "pineapple", dataTitle: "Pineapple" },
    { text: "&#x1F34E;", id: "red-apple", dataTitle: "Red Apple" },
    { text: "&#x1F34F;", id: "green-apple", dataTitle: "Green Apple" },
    { text: "&#x1F350;", id: "pear", dataTitle: "Pear" },
    { text: "&#x1F351;", id: "peach", dataTitle: "Peach" },
    { text: "&#x1F352;", id: "cherries", dataTitle: "Cherries" },
    { text: "&#x1F353;", id: "strawberry", dataTitle: "Strawberry" },
    { text: "&#x1F354;", id: "hamburger", dataTitle: "Hamburger" },
    { text: "&#x1F355;", id: "pizza", dataTitle: "Pizza" },
    { text: "&#x1F356;", id: "meat-on-bone", dataTitle: "Meat on Bone" },
    { text: "&#x1F357;", id: "poultry-leg", dataTitle: "Poultry Leg" },
    { text: "&#x1F358;", id: "rice-cracker", dataTitle: "Rice Cracker" },
    { text: "&#x1F359;", id: "rice-ball", dataTitle: "Rice Ball" },
    { text: "&#x1F35A;", id: "cooked-rice", dataTitle: "Cooked Rice" },
    { text: "&#x1F35B;", id: "curry-and-rice", dataTitle: "Curry and Rice" },
    { text: "&#x1F35C;", id: "steaming-bowl", dataTitle: "Steaming Bowl" },
    { text: "&#x1F35D;", id: "spaghetti", dataTitle: "Spaghetti" },
    { text: "&#x1F35E;", id: "bread", dataTitle: "Bread" },
    { text: "&#x1F35F;", id: "french-fries", dataTitle: "French Fries" },
    { text: "&#x1F360;", id: "roasted-sweet-potato", dataTitle: "Roasted Sweet Potato" },
    { text: "&#x1F361;", id: "dango", dataTitle: "Dango" },
    { text: "&#x1F362;", id: "oden", dataTitle: "Oden" },
    { text: "&#x1F363;", id: "sushi", dataTitle: "Sushi" },
    { text: "&#x1F364;", id: "fried-shrimp", dataTitle: "Fried Shrimp" },
    { text: "&#x1F365;", id: "fish-cake-with-swirl-design", dataTitle: "Fish Cake with Swirl Design" },
    { text: "&#x1F366;", id: "soft-ice-cream", dataTitle: "Soft Ice Cream" },
    { text: "&#x1F367;", id: "shaved-ice", dataTitle: "Shaved Ice" },
    { text: "&#x1F368;", id: "ice-cream", dataTitle: "Ice Cream" },
    { text: "&#x1F369;", id: "doughnut", dataTitle: "Doughnut" },
    { text: "&#x1F36A;", id: "cookie", dataTitle: "Cookie" },
    { text: "&#x1F36B;", id: "chocolate-bar", dataTitle: "Chocolate Bar" },
    { text: "&#x1F36C;", id: "candy", dataTitle: "Candy" },
    { text: "&#x1F36D;", id: "lollipop", dataTitle: "Lollipop" },
    { text: "&#x1F36E;", id: "custard", dataTitle: "Custard" },
    { text: "&#x1F36F;", id: "honey-pot", dataTitle: "Honey Pot" },
    { text: "&#x1F370;", id: "shortcake", dataTitle: "Shortcake" },
    { text: "&#x1F371;", id: "bento-box", dataTitle: "Bento Box" },
    { text: "&#x1F372;", id: "pot-of-food", dataTitle: "Pot of Food" },
    { text: "&#x1F373;", id: "cooking", dataTitle: "Cooking" },
    { text: "&#x1F374;", id: "fork-and-knife", dataTitle: "Fork and Knife" },
    { text: "&#x1F375;", id: "teacup-without-handle", dataTitle: "Teacup Without Handle" },
    { text: "&#x1F376;", id: "sake-bottle-and-cup", dataTitle: "Sake Bottle and Cup" },
    { text: "&#x1F377;", id: "wine-glass", dataTitle: "Wine Glass" },
    { text: "&#x1F378;", id: "cocktail-glass", dataTitle: "Cocktail Glass" },
    { text: "&#x1F379;", id: "tropical-drink", dataTitle: "Tropical Drink" },
    { text: "&#x1F37A;", id: "beer-mug", dataTitle: "Beer Mug" },
    { text: "&#x1F37B;", id: "clinking-beer-mugs", dataTitle: "Clinking Beer Mugs" },
    { text: "&#x1F37C;", id: "baby-bottle", dataTitle: "Baby Bottle" },
];

const activities = [
    /* events & celebrations */
    {
        text: "&#x1F383;",
        id: "pumpkin",
        dataTitle: "Pumpkin"
    },
    {
        text: "&#x1F384;",
        id: "christmas_tree",
        dataTitle: "Christmas Tree"
    },
    {
        text: "&#x1F386;",
        id: "fireworks",
        dataTitle: "Fireworks"
    },
    {
        text: "&#x1F387;",
        id: "sparkler",
        dataTitle: "Sparker"
    },
    {
        text: "&#x1F388;",
        id: "firecracker",
        dataTitle: "Firecracker"
    },
    {
        text: "&#x1F389;",
        id: "balloon",
        dataTitle: "Balloon"
    },
    {
        text: "&#x1F38A;",
        id: "party_popper",
        dataTitle: "Party Popper"
    },
    { text: "&#x1F38B;", id: "tanabata-tree", dataTitle: "Tanabata Tree" },
    { text: "&#x1F38D;", id: "pine-decoration", dataTitle: "Pine Decoration" },
    { text: "&#x1F38E;", id: "japanese-dolls", dataTitle: "Japanese Dolls" },
    { text: "&#x1F38F;", id: "carp-streamer", dataTitle: "Carp Streamer" },
    { text: "&#x1F390;", id: "wind-chime", dataTitle: "Wind Chime" },
    { text: "&#x1F393;", id: "graduation_cap", dataTitle: "Graduation Cap" },

    { text: "&#x1F9E8;", id: "firecracker", dataTitle: "Firecracker" },
    { text: "&#128293;", id: "fire", dataTitle: "Fire" },
    { text: "&#x1F388;", id: "balloon", dataTitle: "Balloon" },
    { text: "&#x1F389;", id: "party-popper", dataTitle: "Party Popper" },
    { text: "&#x1F38A;", id: "confetti-ball", dataTitle: "Confetti Ball" },


    /* deportes */
    { text: "&#x1F3C0;", id: "basketball-and-hoop", dataTitle: "Basketball and Hoop" },
    { text: "&#x1F3C1;", id: "chequered-flag", dataTitle: "Chequered Flag" },
    { text: "&#x1F3C2;", id: "snowboarder", dataTitle: "Snowboarder" },
    { text: "&#x1F3C3;", id: "runner", dataTitle: "Runner" },
    { text: "&#x1F3C4;", id: "surfer", dataTitle: "Surfer" },
    { text: "&#x1F3C6;", id: "trophy", dataTitle: "Trophy" },
    { text: "&#x1F3C8;", id: "american-football", dataTitle: "American Football" },
    { text: "&#x1F3CA;", id: "swimmer", dataTitle: "Swimmer" },
];

const travel_places = [
    /* transportes */
    { text: "&#x1F680;", id: "rocket", dataTitle: "Rocket" },
    { text: "&#x1F681;", id: "helicopter", dataTitle: "Helicopter" },
    { text: "&#x1F682;", id: "steam-locomotive", dataTitle: "Steam Locomotive" },
    { text: "&#x1F683;", id: "railway-car", dataTitle: "Railway Car" },
    { text: "&#x1F684;", id: "bullet-train", dataTitle: "Bullet Train" },
    { text: "&#x1F685;", id: "train", dataTitle: "Train" },
    { text: "&#x1F686;", id: "high-speed-train", dataTitle: "High-Speed Train" },
    { text: "&#x1F687;", id: "high-speed-train-with-bullet-nose", dataTitle: "High-Speed Train with Bullet Nose" },
    { text: "&#x1F688;", id: "light-rail", dataTitle: "Light Rail" },
    { text: "&#x1F689;", id: "metro", dataTitle: "Metro" },
    { text: "&#x1F68A;", id: "station", dataTitle: "Station" },
    { text: "&#x1F68B;", id: "tram", dataTitle: "Tram" },
    { text: "&#x1F68C;", id: "tram-car", dataTitle: "Tram Car" },
    { text: "&#x1F68D;", id: "bus", dataTitle: "Bus" },
    { text: "&#x1F68E;", id: "oncoming-bus", dataTitle: "Oncoming Bus" },
    { text: "&#x1F68F;", id: "trolleybus", dataTitle: "Trolleybus" },
    { text: "&#x1F690;", id: "bus-stop", dataTitle: "Bus Stop" },
    { text: "&#x1F691;", id: "minibus", dataTitle: "Minibus" },
    { text: "&#x1F692;", id: "ambulance", dataTitle: "Ambulance" },
    { text: "&#x1F693;", id: "fire-engine", dataTitle: "Fire Engine" },
    { text: "&#x1F694;", id: "police-car", dataTitle: "Police Car" },
    { text: "&#x1F695;", id: "oncoming-police-car", dataTitle: "Oncoming Police Car" },
    { text: "&#x1F696;", id: "taxi", dataTitle: "Taxi" },
    { text: "&#x1F697;", id: "oncoming-taxi", dataTitle: "Oncoming Taxi" },
    { text: "&#x1F698;", id: "automobile", dataTitle: "Automobile" },
    { text: "&#x1F699;", id: "oncoming-automobile", dataTitle: "Oncoming Automobile" },
    { text: "&#x1F69A;", id: "recreational-vehicle", dataTitle: "Recreational Vehicle" },
    { text: "&#x1F69B;", id: "delivery-truck", dataTitle: "Delivery Truck" },
    { text: "&#x1F69C;", id: "articulated-lorry", dataTitle: "Articulated Lorry" },
    { text: "&#x1F69D;", id: "tractor", dataTitle: "Tractor" },
    { text: "&#x1F69E;", id: "monorail", dataTitle: "Monorail" },
    { text: "&#x1F69F;", id: "mountain-railway", dataTitle: "Mountain Railway" },
    { text: "&#x1F6A0;", id: "suspension-railway", dataTitle: "Suspension Railway" },
    { text: "&#x1F6A1;", id: "mountain-cableway", dataTitle: "Mountain Cableway" },
    { text: "&#x1F9BD;", id: "manual-wheelchair", dataTitle: "Manual Wheelchair" },
    { text: "&#x1F9BE;", id: "motorized-wheelchair", dataTitle: "Motorized Wheelchair" },
    { text: "&#x1F6F5;", id: "motor-scooter", dataTitle: "Motor Scooter" },
    { text: "&#x1F6F4;", id: "kick-scooter", dataTitle: "Kick Scooter" },
    { text: "&#x1F6B2;", id: "bicycle", dataTitle: "Bicycle" },
    { text: "&#x1F6F6;", id: "canoe", dataTitle: "Canoe" },
    { text: "&#x1F6F9;", id: "skateboard", dataTitle: "Skateboard" },

    /* buildings */
    { text: "&#x1F3E0;", id: "house-building", dataTitle: "House Building" },
    { text: "&#x1F3E1;", id: "house-with-garden", dataTitle: "House with Garden" },
    { text: "&#x1F3E2;", id: "office-building", dataTitle: "Office Building" },
    { text: "&#x1F3E3;", id: "japanese-post-office", dataTitle: "Japanese Post Office" },
    { text: "&#x1F3E4;", id: "post-office", dataTitle: "Post Office" },
    { text: "&#x1F3E5;", id: "hospital", dataTitle: "Hospital" },
    { text: "&#x1F3E6;", id: "bank", dataTitle: "Bank" },
    { text: "&#x1F3E7;", id: "hotel", dataTitle: "Hotel" },
    { text: "&#x1F3E8;", id: "love-hotel", dataTitle: "Love Hotel" },
    { text: "&#x1F3E9;", id: "convenience-store", dataTitle: "Convenience Store" },
    { text: "&#x1F3EA;", id: "school", dataTitle: "School" },
    { text: "&#x1F3EB;", id: "department-store", dataTitle: "Department Store" },
    { text: "&#x1F3EC;", id: "factory", dataTitle: "Factory" },
    { text: "&#x1F3ED;", id: "izakaya-lantern", dataTitle: "Izakaya Lantern" },
    { text: "&#127983;", id: "japanese-castle", dataTitle: "Japanese Castle" },
    { text: "&#127984;", id: "european-castle", dataTitle: "European Castle" }
];

const symbols = [
    /*hearts*/
    { text: "&#129505;", id: "orange-heart", dataTitle: "Orange Heart" },
    { text: "&#128151;", id: "heart-with-ribbon", dataTitle: "Heart with Ribbon" },
    { text: "&#128152;", id: "revolving-hearts", dataTitle: "Revolving Hearts" },
    { text: "&#128153;", id: "heart-decoration", dataTitle: "Heart Decoration" },
    { text: "&#x1F493;", id: "beating-heart", dataTitle: "Beating Heart" },
    { text: "&#x1F494;", id: "broken-heart", dataTitle: "Broken Heart" },
    { text: "&#x1F495;", id: "two-hearts", dataTitle: "Two Hearts" },
    { text: "&#x1F496;", id: "sparkling-heart", dataTitle: "Sparkling Heart" },
    { text: "&#x1F497;", id: "growing-heart", dataTitle: "Growing Heart" },
    { text: "&#x1F498;", id: "heart-with-arrow", dataTitle: "Heart with Arrow" },
    { text: "&#x1F499;", id: "blue-heart", dataTitle: "Blue Heart" },
    { text: "&#x1F49A;", id: "green-heart", dataTitle: "Green Heart" },
    { text: "&#x1F49B;", id: "yellow-heart", dataTitle: "Yellow Heart" },
    { text: "&#x1F49C;", id: "purple-heart", dataTitle: "Purple Heart" },
    { text: "&#x1F49D;", id: "heart-with-ribbon", dataTitle: "Heart with Ribbon" },
    { text: "&#x1F49E;", id: "revolving-hearts", dataTitle: "Revolving Hearts" },
    { text: "&#x1F49F;", id: "heart-decoration", dataTitle: "Heart Decoration" },
    { text: "&#x1F48C;", id: "love-letter", dataTitle: "Love Letter" },
    { text: "&#x1F48B;", id: "kiss-mark", dataTitle: "Kiss Mark" },

    { text: "&#x2660;", id: "black-spade-suit", dataTitle: "Black spade suit" },
    { text: "&#x2663;", id: "black-club-suit", dataTitle: "Black club suit" },
    { text: "&#x2665;", id: "black-heart-suit", dataTitle: "Black heart suit" },
    { text: "&#x2666;", id: "black-diamond-suit", dataTitle: "Black diamond suit" },
    { text: "&#x2648;", id: "aries", dataTitle: "Aries" },
    { text: "&#x2649;", id: "taurus", dataTitle: "Taurus" },
    { text: "&#x264a;", id: "gemini", dataTitle: "gemini" },
    { text: "&#x264b;", id: "cancer", dataTitle: "Cancer" },
    { text: "&#x264c;", id: "leo", dataTitle: "Leo" },
    { text: "&#x264d;", id: "virgo", dataTitle: "virgo" },
    { text: "&#x264e;", id: "libra", dataTitle: "Libra" },
    { text: "&#x264f;", id: "scorpius", dataTitle: "Scorpius" },
    { text: "&#x2650;", id: "sagittarius", dataTitle: "Sagittarius" },
    { text: "&#x2651;", id: "capricorn", dataTitle: "Capricorn" },
    { text: "&#x2652;", id: "aquarius", dataTitle: "Aquarius" },
    { text: "&#x2653;", id: "pisces", dataTitle: "Pisces" },
    { text: "&#x26ce;", id: "ophiuchus", dataTitle: "ophiuchus" },
    { text: "&#x1f500;", id: "twisted-rightwards-arrows", dataTitle: "Twisted rightwards arrows" },
    { text: "&#x1f501;", id: "clockwise-rightwards-and-leftwards-open-circle-arrows", dataTitle: "Clockwise rightwards and leftwards open circle arrows" },
    { text: "&#x1f502;", id: "clockwise-rightwards-and-leftwards-open-circle-arrows-with-circled-one-overlay", dataTitle: "Clockwise rightwards and leftwards open circle arrows with circled one overlay" },
    { text: "&#x1f503;", id: "clockwise-downwards-and-upwards-open-circle-arrows", dataTitle: "Clockwise downwards and upwards open circle arrows" },
    { text: "&#x1f504;", id: "anticlockwise-downwards-and-upwards-open-circle-arrows", dataTitle: "Anticlockwise downwards and upwards open circle arrows" },


    {
        text: "&#x26A0;",
        id: "warning",
        dataTitle: "Warning"
      },
      {
        text: "&#x1F6B8;",
        id: "children_crossing",
        dataTitle: "Children Crossing"
      },
      {
        text: "&#x26D4;",
        id: "no_entry",
        dataTitle: "No Entry"
      },
      {
        text: "&#x1F6AD;",
        id: "no_smoking",
        dataTitle: "No Smoking"
      },
      {
        text: "&#x1F6B1;",
        id: "no_drinking",
        dataTitle: "No Drinking"
      },
      {
        text: "&#x1F4F5;",
        id: "no_cell_phones",
        dataTitle: "No Mobile Phones"
      },
      {
        text: "&#x1F51E;",
        id: "underage",
        dataTitle: "Underage"
      },
      {
        text: "&#x2622;",
        id: "radioactive",
        dataTitle: "Radioactive"
      },

];

/* Flags
{ text: "&#x1F1E6;&#x1F1E8;", id: "flag-for-Andorra", dataTitle: "Flag for Andorra" },
{ text: "&#x1F1E6;&#x1F1E9;", id: "flag-for-United-Arab-Emirates", dataTitle: "Flag for United Arab Emirates" },
{ text: "&#x1F1E6;&#x1F1EA;", id: "flag-for-Afghanistan", dataTitle: "Flag for Afghanistan" },
{ text: "&#x1F1E6;&#x1F1EB;", id: "flag-for-Antigua-and-Barbuda", dataTitle: "Flag for Antigua and Barbuda" },
{ text: "&#x1F1E6;&#x1F1EC;", id: "flag-for-Anguilla", dataTitle: "Flag for Anguilla" },
{ text: "&#x1F1E6;&#x1F1EE;", id: "flag-for-Albania", dataTitle: "Flag for Albania" },
{ text: "&#x1F1E6;&#x1F1F1;", id: "flag-for-Armenia", dataTitle: "Flag for Armenia" },
{ text: "&#x1F1E6;&#x1F1F2;", id: "flag-for-Angola", dataTitle: "Flag for Angola" },
{ text: "&#x1F1E6;&#x1F1F4;", id: "flag-for-Argentina", dataTitle: "Flag for Argentina" },
{ text: "&#x1F1E6;&#x1F1F6;", id: "flag-for-American-Samoa", dataTitle: "Flag for American Samoa" },
{ text: "&#x1F1E6;&#x1F1F7;", id: "flag-for-Austria", dataTitle: "Flag for Austria" },
{ text: "&#x1F1E6;&#x1F1F8;", id: "flag-for-Australia", dataTitle: "Flag for Australia" },
{ text: "&#x1F1E6;&#x1F1F9;", id: "flag-for-Aruba", dataTitle: "Flag for Aruba" },
{ text: "&#x1F1E6;&#x1F1FA;", id: "flag-for-Åland-Islands", dataTitle: "Flag for Åland Islands" },
{ text: "&#x1F1E6;&#x1F1FC;", id: "flag-for-Azerbaijan", dataTitle: "Flag for Azerbaijan" },
{ text: "&#x1F1E6;&#x1F1FD;", id: "flag-for-Bosnia-and-Herzegovina", dataTitle: "Flag for Bosnia and Herzegovina" },
{ text: "&#x1F1E6;&#x1F1FF;", id: "flag-for-Barbados", dataTitle: "Flag for Barbados" },
{ text: "&#x1F1E7;&#x1F1E6;", id: "flag-for-Bangladesh", dataTitle: "Flag for Bangladesh" },
{ text: "&#x1F1E7;&#x1F1E7;", id: "flag-for-Belgium", dataTitle: "Flag for Belgium" },
{ text: "&#x1F1E7;&#x1F1E9;", id: "flag-for-Burkina-Faso", dataTitle: "Flag for Burkina Faso" },
{ text: "&#x1F1E7;&#x1F1EA;", id: "flag-for-Bulgaria", dataTitle: "Flag for Bulgaria" },
{ text: "&#x1F1E7;&#x1F1EB;", id: "flag-for-Bahrain", dataTitle: "Flag for Bahrain" }
*/

/* 

*/


export default { smileys, people, animals_nature, food_drinks, activities, travel_places, symbols };







