const emojis = [

    /* smileys */
    { text: "&#x1F600;", id: "grinning-face", title: "Grinning Face" },
    { text: "&#x1F601;", id: "grinning-face-with-smiling-eyes", title: "grinning face with smiling eyes" },
    { text: "&#x1F602;", id: "face-with-tears-of-joy", title: "Face with tears of joy" },
    { text: "&#x1F603;", id: "smiling-face-with-open-mouth", title: "Smiling face with open mouth" },
    { text: "&#x1F604;", id: "smiling-face-with-open-mouth-and-smiling-eyes", title: "Smiling face with open mouth and smiling eyes" },
    { text: "&#x1F605;", id: "smiling-face-with-open-mouth-and-cold-sweat", title: "Smiling face with open mouth and cold sweat" },
    { text: "&#x1F606;", id: "smiling-face-with-open-mouth-and-tightly-closed-eyes", title: "Smiling face with open mouth and tightly-closed eyes" },
    { text: "&#x1F607;", id: "smiling-face-with-halo", title: "Smiling face with halo" },
    { text: "&#x1F608;", id: "smiling-face-with-horns", title: "Smiling face with horns" },
    { text: "&#x1F609;", id: "winking-face", title: "winking face" },
    { text: "&#x1F60A;", id: "smiling-face-with-smiling-eyes", title: "Smiling face with smiling eyes" },
    { text: "&#x1F60B;", id: "face-savouring-delicious-food", title: "Face savouring delicious food" },
    { text: "&#x1F60C;", id: "relieved-face", title: "relieved face" },
    { text: "&#x1F60D;", id: "smiling-face-with-heart-shaped-eyes", title: "Smiling face with heart-shaped eyes" },
    { text: "&#x1F60E;", id: "smiling-face-with-sunglasses", title: "Smiling face with sunglasses" },
    { text: "&#x1F60F;", id: "smirking-face", title: "Smirking face" },
    { text: "&#x1F610;", id: "neutral-face", title: "neutral face" },
    { text: "&#x1F611;", id: "expressionless-face", title: "expressionless face" },
    { text: "&#x1F612;", id: "unamused-face", title: "unamused face" },
    { text: "&#x1F613;", id: "face-with-cold-sweat", title: "Face with cold sweat" },
    { text: "&#x1F614;", id: "pensive-face", title: "Pensive face" },
    { text: "&#x1F615;", id: "confused-face", title: "Confused face" },
    { text: "&#x1F616;", id: "confounded-face", title: "Confounded face" },
    { text: "&#x1F617;", id: "kissing-face", title: "kissing face" },
    { text: "&#x1F618;", id: "face-throwing-a-kiss", title: "Face throwing a kiss" },
    { text: "&#x1F619;", id: "kissing-face-with-smiling-eyes", title: "kissing face with smiling eyes" },
    { text: "&#x1F61A;", id: "kissing-face-with-closed-eyes", title: "kissing face with closed eyes" },
    { text: "&#x1F61B;", id: "face-with-stuck-out-tongue", title: "Face with stuck-out tongue" },
    { text: "&#x1F61C;", id: "face-with-stuck-out-tongue-and-winking-eye", title: "Face with stuck-out tongue and winking eye" },
    { text: "&#x1F61D;", id: "face-with-stuck-out-tongue-and-tightly-closed-eyes", title: "Face with stuck-out tongue and tightly-closed eyes" },
    { text: "&#x1F61E;", id: "disappointed-face", title: "Disappointed face" },
    { text: "&#x1F61F;", id: "worried-face", title: "worried face" },
    { text: "&#x1F620;", id: "angry-face", title: "Angry face" },
    { text: "&#x1F621;", id: "pouting-face", title: "Pouting face" },
    { text: "&#x1F622;", id: "crying-face", title: "Crying face" },
    { text: "&#x1F623;", id: "persevering-face", title: "Persevering face" },
    { text: "&#x1F624;", id: "face-with-look-of-triumph", title: "Face with look of triumph" },
    { text: "&#x1F625;", id: "disappointed-but-relieved-face", title: "Disappointed but relieved face" },
    { text: "&#x1F626;", id: "frowning-face-with-open-mouth", title: "Frowning face with open mouth" },
    { text: "&#x1F627;", id: "anguished-face", title: "Anguished face" },
    { text: "&#x1F628;", id: "fearful-face", title: "Fearful face" },
    { text: "&#x1F629;", id: "weary-face", title: "weary face" },
    { text: "&#x1F62A;", id: "sleepy-face", title: "Sleepy face" },
    { text: "&#x1F62B;", id: "tired-face", title: "Tired face" },
    { text: "&#x1F62C;", id: "grimacing-face", title: "grimacing face" },
    { text: "&#x1F62D;", id: "loudly-crying-face", title: "Loudly crying face" },
    { text: "&#x1F62E;", id: "face-with-open-mouth", title: "Face with open mouth" },
    { text: "&#x1F62F;", id: "hushed-face", title: "Hushed face" },
    { text: "&#x1F630;", id: "face-with-open-mouth-and-cold-sweat", title: "Face with open mouth and cold sweat" },
    { text: "&#x1F631;", id: "face-screaming-in-fear", title: "Face screaming in fear" },
    { text: "&#x1F632;", id: "astonished-face", title: "Astonished face" },
    { text: "&#x1F633;", id: "flushed-face", title: "Flushed face" },
    { text: "&#x1F634;", id: "sleeping-face", title: "Sleeping face" },
    { text: "&#x1F635;", id: "dizzy-face", title: "Dizzy face" },
    { text: "&#x1F636;", id: "face-without-mouth", title: "Face without mouth" },
    { text: "&#x1F637;", id: "face-with-medical-mask", title: "Face with medical mask" },
    { text: "&#x1F641;", id: "slightly-frowning-face", title: "Slightly frowning face" },
    { text: "&#x1F642;", id: "slightly-smiling-face", title: "Slightly smiling face" },
    { text: "&#x1F643;", id: "upside-down-face", title: "upside-down face" },
    { text: "&#x1F644;", id: "face-with-rolling-eyes", title: "Face with rolling eyes" },
    { text: "&#x1F910;", id: "zipper-mouth-face", title: "zipper-mouth face" },
    { text: "&#x1F911;", id: "money-mouth-face", title: "Money-mouth face" },
    { text: "&#x1F912;", id: "face-with-thermometer", title: "Face with thermometer" },
    { text: "&#x1F913;", id: "nerd-face", title: "nerd face" },
    { text: "&#x1F914;", id: "thinking-face", title: "Thinking face" },
    { text: "&#x1F915;", id: "face-with-head-bandage", title: "Face with head-bandage" },
    { text: "&#x1f920;", id: "face-with-cowboy-hat", title: "Face with cowboy hat" },
    { text: "&#x1f921;", id: "clown-face", title: "Clown face" },
    { text: "&#x1f922;", id: "nauseated-face", title: "nauseated face" },
    { text: "&#x1f923;", id: "rolling-on-the-floor-laughing", title: "rolling on the floor laughing" },
    { text: "&#x1f924;", id: "drooling-face", title: "Drooling face" },
    { text: "&#x1f925;", id: "lying-face", title: "Lying face" },
    { text: "&#x1f927;", id: "shushing-face", title: "Shushing face" },
    { text: "&#x1f928;", id: "face-with-hand-over-mouth", title: "Face with hand over mouth" },
    { text: "&#x1f929;", id: "grinning-face-with-star-eyes", title: "grinning face with star eyes" },
    { text: "&#x1f92a;", id: "grinning-face-with-one-large-and-one-small-eye", title: "grinning face with one large and one small eye" },
    { text: "&#x1f92b;", id: "face-with-finger-covering-closed-lips", title: "Face with finger covering closed lips" },
    { text: "&#x1f92c;", id: "serious-face-with-symbols-covering-mouth", title: "Serious face with symbols covering mouth" },
    { text: "&#x1f92d;", id: "smiling-face-with-smiling-eyes-and-hand-covering-mouth", title: "Smiling face with smiling eyes and hand covering mouth" },
    { text: "&#x1f92e;", id: "face-with-open-mouth-vomiting", title: "Face with open mouth vomiting" },
    { text: "&#x1f92f;", id: "shocked-face-with-exploding-head", title: "Shocked face with exploding head" },
    { text: "&#x1f9d0;", id: "face-with-monocle", title: "Face with monocle" },
    { text: "&#x1F4A9;", id: "pile-of-poo", title: "Pile of poo" },
    { text: "&#x1F638;", id: "grinning-cat-face-with-smiling-eyes", title: "grinning cat face with smiling eyes" },
    { text: "&#x1F639;", id: "cat-face-with-tears-of-joy", title: "cat face with tears of joy" },
    { text: "&#x1F63A;", id: "smiling-cat-face-with-open-mouth", title: "smiling cat face with open mouth" },
    { text: "&#x1F63B;", id: "smiling-cat-face-with-heart-shaped-eyes", title: "smiling cat face with heart-shaped eyes" },
    { text: "&#x1F63C;", id: "cat-face-with-wry-smile", title: "cat face with wry smile" },
    { text: "&#x1F63D;", id: "kissing-cat-face-with-closed-eyes", title: "kissing cat face with closed eyes" },
    { text: "&#x1F63E;", id: "pouting-cat-face", title: "pouting cat face" },
    { text: "&#x1F63F;", id: "crying-cat-face", title: "crying cat face" },
    { text: "&#x1F640;", id: "weary-cat-face", title: "weary cat face" },
    { text: "&#x1F648;", id: "see-no-evil-monkey", title: "see-no-evil monkey" },
    { text: "&#x1F649;", id: "hear-no-evil-monkey", title: "hear-no-evil monkey" },
    { text: "&#x1F64A;", id: "speak-no-evil-monkey", title: "speak-no-evil monkey" },

    /* hands */
    { text: "&#x261d;", id: "white-up-pointing-index", title: "white up pointing index" },
    { text: "&#x270a;", id: "raised-fist", title: "raised fist" },
    { text: "&#x270b;", id: "raised-hand", title: "raised hand" },
    { text: "&#x1F590;", id: "raised-hand-with-fingers-splayed", title: "raised hand with fingers splayed" },
    { text: "&#x270c;", id: "victory-hand", title: "victory hand" },
    { text: "&#x270d;", id: "writing-hand", title: "writing hand" },
    { text: "&#x1f44a;", id: "fisted-hand-sign", title: "Fisted hand sign" },
    { text: "&#x1f44b;", id: "waving-hand-sign", title: "waving hand sign" },
    { text: "&#x1f44c;", id: "ok-hand-sign", title: "ok hand sign" },
    { text: "&#x1f44d;", id: "thumbs-up-sign", title: "Thumbs up sign" },
    { text: "&#x1f44e;", id: "thumbs-down-sign", title: "Thumbs down sign" },
    { text: "&#x1f44f;", id: "clapping-hands-sign", title: "Clapping hands sign" },
    { text: "&#x1f450;", id: "open-hands-sign", title: "open hands sign" },
    { text: "&#x1f64c;", id: "person-raising-both-hands-in-celebration", title: "Person raising both hands in celebration" },
    { text: "&#x1f64f;", id: "person-with-folded-hands", title: "Person with folded hands" },
    { text: "&#x1f91a;", id: "raised-back-of-hand", title: "raised back of hand" },
    { text: "&#x1f91b;", id: "left-facing-fist", title: "Left-facing fist" },
    { text: "&#x1f91c;", id: "right-facing-fist", title: "right-facing fist" },
    { text: "&#x1f91e;", id: "hand-with-index-and-middle-fingers-crossed", title: "Hand with index and middle fingers crossed" },
    { text: "&#x1f91f;", id: "i-love-you-hand-sign", title: "I love you hand sign" },
    { text: "&#x1f918;", id: "sign-of-the-horns", title: "Sign of the horns" },
    { text: "&#x1f919;", id: "call-me-hand", title: "Call me hand" },
    { text: "&#x1f448;", id: "white-left-pointing-backhand-index", title: "white left pointing backhand index" },
    { text: "&#x1f449;", id: "white-right-pointing-backhand-index", title: "white right pointing backhand index" },
    { text: "&#x1f446;", id: "white-up-pointing-backhand-index", title: "white up pointing backhand index" },
    { text: "&#x1f447;", id: "white-down-pointing-backhand-index", title: "white down pointing backhand index" },
    { text: "&#x1f595;", id: "reversed-hand-with-middle-finger-extended", title: "reversed hand with middle finger extended" },
    { text: "&#x1F596;", id: "raised-hand-with-part-between-middle-and-ring-fingers", title: "raised hand with part between middle and ring fingers" },
    { text: "&#x1F932;", id: "palms-up-together", title: "Palms up together" },
    { text: "&#x1F4AA;", id: "flexed-biceps", title: "Flexed biceps" },
    { text: "&#x1F91D;", id: "handshake", title: "Handshake" },
    { text: "&#x1F485;", id: "nail-polish", title: "nail polish" },
    { text: "&#x1F933;", id: "selfie", title: "Selfie" },

    /* other characters */
    { text: "&#x1F9D9;", id: "mage", title: "Mage" },
    { text: "&#x1F9DA;", id: "fairy", title: "Fairy" },
    { text: "&#x1F9DB;", id: "vampire", title: "Vampire" },
    { text: "&#x1F9DC;", id: "merperson", title: "Merperson" },
    { text: "&#x1F9DD;", id: "elf", title: "Elf" },
    { text: "&#x1F9DE;", id: "genie", title: "Genie" },
    { text: "&#x1F9DF;", id: "zombie", title: "Zombie" },
    { text: "&#x1F916;", id: "robot-face", title: "robot face" },
    { text: "&#x1F9D8;", id: "person-in-lotus-position", title: "Person in lotus position" },
    { text: "&#x1F9D5;", id: "person-with-headscarf", title: "Person with headscarf" },
    { text: "&#x1F931;", id: "breast-feeding", title: "Breast-feeding" },
    { text: "&#x1F930;", id: "pregnant-woman", title: "Pregnant-woman" },
    { text: "&#x1F466;", id: "boy", title: "Boy" },
    { text: "&#x1F467;", id: "girl", title: "Girl" },
    { text: "&#x1F468;", id: "man", title: "Man" },
    { text: "&#x1F469;", id: "woman", title: "Woman" },
    { text: "&#x1F476;", id: "baby", title: "Baby" },
    { text: "&#x1F475;", id: "older-woman", title: "Older Woman" },
    { text: "&#x1F474;", id: "older-man", titl: "Older Man" },
    { text: "&#x1F479;", id: "japanese-ogre", title: "Japanese Ogre" },
    { text: "&#x1F47A;", id: "japanese-goblin", title: "Japanese Goblin" },
    { text: "&#x1F480;", id: "skull", title: "Skull" },
    { text: "&#x1F47B;", id: "ghost", title: "Ghost" },
    { text: "&#x1F47D;", id: "extraterrestrial-alien", title: "Extraterrestrial Alien" },
    { text: "&#x1F47E;", id: "alien-monster", title: "Alien Monster / Space Invader" },
    { text: "&#x1F47F;", id: "imp", title: "Imp" },
    { text: "&#x1F383;", id: "jack-o-lantern", title: "Jack-O-Lantern" },
    { text: "&#x1F385;", id: "father-christmas", title: "Father Christmas" },

    /*hearts*/
    { text: "&#129505;", id: "orange-heart", title: "Orange Heart" },
    { text: "&#128151;", id: "heart-with-ribbon", title: "Heart with Ribbon" },
    { text: "&#128152;", id: "revolving-hearts", title: "Revolving Hearts" },
    { text: "&#128153;", id: "heart-decoration", title: "Heart Decoration" },
    { text: "&#x1F493;", id: "beating-heart", title: "Beating Heart" },
    { text: "&#x1F494;", id: "broken-heart", title: "Broken Heart" },
    { text: "&#x1F495;", id: "two-hearts", title: "Two Hearts" },
    { text: "&#x1F496;", id: "sparkling-heart", title: "Sparkling Heart" },
    { text: "&#x1F497;", id: "growing-heart", title: "Growing Heart" },
    { text: "&#x1F498;", id: "heart-with-arrow", title: "Heart with Arrow" },
    { text: "&#x1F499;", id: "blue-heart", title: "Blue Heart" },
    { text: "&#x1F49A;", id: "green-heart", title: "Green Heart" },
    { text: "&#x1F49B;", id: "yellow-heart", title: "Yellow Heart" },
    { text: "&#x1F49C;", id: "purple-heart", title: "Purple Heart" },
    { text: "&#x1F49D;", id: "heart-with-ribbon", title: "Heart with Ribbon" },
    { text: "&#x1F49E;", id: "revolving-hearts", title: "Revolving Hearts" },
    { text: "&#x1F49F;", id: "heart-decoration", title: "Heart Decoration" },
    { text: "&#x1F48C;", id: "love-letter", title: "Love Letter" },
    { text: "&#x1F48B;", id: "kiss-mark", title: "Kiss Mark" },

    /* animals */
    { text: "&#x1F400;", id: "rat", title: "Rat" },
    { text: "&#x1F401;", id: "mouse", title: "Mouse" },
    { text: "&#x1F402;", id: "ox", title: "Ox" },
    { text: "&#x1F403;", id: "water-buffalo", title: "Water Buffalo" },
    { text: "&#x1F404;", id: "cow", title: "Cow" },
    { text: "&#x1F405;", id: "tiger", title: "Tiger" },
    { text: "&#x1F406;", id: "leopard", title: "Leopard" },
    { text: "&#x1F407;", id: "rabbit", title: "Rabbit" },
    { text: "&#x1F408;", id: "cat", title: "Cat" },
    { text: "&#x1F409;", id: "dragon", title: "Dragon" },
    { text: "&#x1F40A;", id: "crocodile", title: "Crocodile" },
    { text: "&#x1F40B;", id: "whale", title: "Whale" },
    { text: "&#x1F40C;", id: "snail", title: "Snail" },
    { text: "&#x1F40D;", id: "snake", title: "Snake" },
    { text: "&#x1F40E;", id: "horse", title: "Horse" },
    { text: "&#x1F40F;", id: "ram", title: "Ram" },
    { text: "&#x1F410;", id: "goat", title: "Goat" },
    { text: "&#x1F411;", id: "sheep", title: "Sheep" },
    { text: "&#x1F412;", id: "monkey", title: "Monkey" },
    { text: "&#x1F413;", id: "rooster", title: "Rooster" },
    { text: "&#x1F414;", id: "chicken", title: "Chicken" },
    { text: "&#x1F415;", id: "dog", title: "Dog" },
    { text: "&#x1F416;", id: "pig", title: "Pig" },
    { text: "&#x1F417;", id: "boar", title: "Boar" },
    { text: "&#x1F418;", id: "elephant", title: "Elephant" },
    { text: "&#x1F419;", id: "octopus", title: "Octopus" },
    { text: "&#x1F41A;", id: "spiral-shell", title: "Spiral Shell" },
    { text: "&#x1F41B;", id: "bug", title: "Bug" },
    { text: "&#x1F41C;", id: "ant", title: "Ant" },
    { text: "&#x1F41D;", id: "honeybee", title: "Honeybee" },
    { text: "&#x1F41E;", id: "lady-beetle", title: "Lady Beetle" },
    { text: "&#x1F41F;", id: "fish", title: "Fish" },
    { text: "&#x1F420;", id: "tropical-fish", title: "Tropical Fish" },
    { text: "&#x1F421;", id: "blowfish", title: "Blowfish" },
    { text: "&#x1F422;", id: "turtle", title: "Turtle" },
    { text: "&#x1F423;", id: "hatching-chick", title: "Hatching Chick" },
    { text: "&#x1F424;", id: "baby-chick", title: "Baby Chick" },
    { text: "&#x1F425;", id: "front-facing-baby-chick", title: "Front-Facing Baby Chick" },
    { text: "&#x1F426;", id: "bird", title: "Bird" },
    { text: "&#x1F427;", id: "penguin", title: "Penguin" },
    { text: "&#x1F428;", id: "koala", title: "Koala" },
    { text: "&#x1F429;", id: "poodle", title: "Poodle" },
    { text: "&#x1F42A;", id: "dromedary-camel", title: "Dromedary Camel" },
    { text: "&#x1F42B;", id: "bactrian-camel", title: "Bactrian Camel" },
    { text: "&#x1F42C;", id: "dolphin", title: "Dolphin" },
    { text: "&#x1F42D;", id: "mouse-face", title: "Mouse Face" },
    { text: "&#x1F42E;", id: "cow-face", title: "Cow Face" },
    { text: "&#x1F42F;", id: "tiger-face", title: "Tiger Face" },
    { text: "&#x1F430;", id: "rabbit-face", title: "Rabbit Face" },
    { text: "&#x1F431;", id: "cat-face", title: "Cat Face" },
    { text: "&#x1F432;", id: "dragon-face", title: "Dragon Face" },
    { text: "&#x1F433;", id: "spouting-whale", title: "Spouting Whale" },
    { text: "&#x1F434;", id: "horse-face", title: "Horse Face" },
    { text: "&#x1F435;", id: "monkey-face", title: "Monkey Face" },
    { text: "&#x1F436;", id: "dog-face", title: "Dog Face" },
    { text: "&#x1F437;", id: "pig-face", title: "Pig Face" },
    { text: "&#x1F438;", id: "frog-face", title: "Frog Face" },
    { text: "&#x1F439;", id: "hamster-face", title: "Hamster Face" },
    { text: "&#x1F43A;", id: "wolf-face", title: "Wolf Face" },
    { text: "&#x1F43B;", id: "bear-face", title: "Bear Face" },
    { text: "&#x1F43C;", id: "panda-face", title: "Panda Face" },
    { text: "&#x1F43D;", id: "pig-nose", title: "Pig Nose" },
    { text: "&#x1F43E;", id: "paw-prints", title: "Paw Prints" },


    /* food & drinks*/
    { text: "&#x1F32D;", id: "hot-dog", title: "Hot Dog" },
    { text: "&#x1F32E;", id: "taco", title: "Taco" },
    { text: "&#x1F32F;", id: "burrito", title: "Burrito" },
    { text: "&#x1F344;", id: "mushroom", title: "Mushroom" },
    { text: "&#x1F345;", id: "tomato", title: "Tomato" },
    { text: "&#x1F346;", id: "aubergine", title: "Aubergine" },
    { text: "&#x1F347;", id: "grapes", title: "Grapes" },
    { text: "&#x1F348;", id: "melon", title: "Melon" },
    { text: "&#x1F349;", id: "watermelon", title: "Watermelon" },
    { text: "&#x1F34A;", id: "tangerine", title: "Tangerine" },
    { text: "&#x1F34B;", id: "lemon", title: "Lemon" },
    { text: "&#x1F34C;", id: "banana", title: "Banana" },
    { text: "&#x1F34D;", id: "pineapple", title: "Pineapple" },
    { text: "&#x1F34E;", id: "red-apple", title: "Red Apple" },
    { text: "&#x1F34F;", id: "green-apple", title: "Green Apple" },
    { text: "&#x1F350;", id: "pear", title: "Pear" },
    { text: "&#x1F351;", id: "peach", title: "Peach" },
    { text: "&#x1F352;", id: "cherries", title: "Cherries" },
    { text: "&#x1F353;", id: "strawberry", title: "Strawberry" },
    { text: "&#x1F354;", id: "hamburger", title: "Hamburger" },
    { text: "&#x1F355;", id: "pizza", title: "Pizza" },
    { text: "&#x1F356;", id: "meat-on-bone", title: "Meat on Bone" },
    { text: "&#x1F357;", id: "poultry-leg", title: "Poultry Leg" },
    { text: "&#x1F358;", id: "rice-cracker", title: "Rice Cracker" },
    { text: "&#x1F359;", id: "rice-ball", title: "Rice Ball" },
    { text: "&#x1F35A;", id: "cooked-rice", title: "Cooked Rice" },
    { text: "&#x1F35B;", id: "curry-and-rice", title: "Curry and Rice" },
    { text: "&#x1F35C;", id: "steaming-bowl", title: "Steaming Bowl" },
    { text: "&#x1F35D;", id: "spaghetti", title: "Spaghetti" },
    { text: "&#x1F35E;", id: "bread", title: "Bread" },
    { text: "&#x1F35F;", id: "french-fries", title: "French Fries" },
    { text: "&#x1F360;", id: "roasted-sweet-potato", title: "Roasted Sweet Potato" },
    { text: "&#x1F361;", id: "dango", title: "Dango" },
    { text: "&#x1F362;", id: "oden", title: "Oden" },
    { text: "&#x1F363;", id: "sushi", title: "Sushi" },
    { text: "&#x1F364;", id: "fried-shrimp", title: "Fried Shrimp" },
    { text: "&#x1F365;", id: "fish-cake-with-swirl-design", title: "Fish Cake with Swirl Design" },
    { text: "&#x1F366;", id: "soft-ice-cream", title: "Soft Ice Cream" },
    { text: "&#x1F367;", id: "shaved-ice", title: "Shaved Ice" },
    { text: "&#x1F368;", id: "ice-cream", title: "Ice Cream" },
    { text: "&#x1F369;", id: "doughnut", title: "Doughnut" },
    { text: "&#x1F36A;", id: "cookie", title: "Cookie" },
    { text: "&#x1F36B;", id: "chocolate-bar", title: "Chocolate Bar" },
    { text: "&#x1F36C;", id: "candy", title: "Candy" },
    { text: "&#x1F36D;", id: "lollipop", title: "Lollipop" },
    { text: "&#x1F36E;", id: "custard", title: "Custard" },
    { text: "&#x1F36F;", id: "honey-pot", title: "Honey Pot" },
    { text: "&#x1F370;", id: "shortcake", title: "Shortcake" },
    { text: "&#x1F371;", id: "bento-box", title: "Bento Box" },
    { text: "&#x1F372;", id: "pot-of-food", title: "Pot of Food" },
    { text: "&#x1F373;", id: "cooking", title: "Cooking" },
    { text: "&#x1F374;", id: "fork-and-knife", title: "Fork and Knife" },
    { text: "&#x1F375;", id: "teacup-without-handle", title: "Teacup Without Handle" },
    { text: "&#x1F376;", id: "sake-bottle-and-cup", title: "Sake Bottle and Cup" },
    { text: "&#x1F377;", id: "wine-glass", title: "Wine Glass" },
    { text: "&#x1F378;", id: "cocktail-glass", title: "Cocktail Glass" },
    { text: "&#x1F379;", id: "tropical-drink", title: "Tropical Drink" },
    { text: "&#x1F37A;", id: "beer-mug", title: "Beer Mug" },
    { text: "&#x1F37B;", id: "clinking-beer-mugs", title: "Clinking Beer Mugs" },
    { text: "&#x1F37C;", id: "baby-bottle", title: "Baby Bottle" },

    /* plants */
    { text: "&#x1F330;", id: "chestnut", title: "Chestnut" },
    { text: "&#x1F331;", id: "seedling", title: "Seedling" },
    { text: "&#x1F332;", id: "evergreen-tree", title: "Evergreen Tree" },
    { text: "&#x1F333;", id: "deciduous-tree", title: "Deciduous Tree" },
    { text: "&#x1F334;", id: "palm-tree", title: "Palm Tree" },
    { text: "&#x1F335;", id: "cactus", title: "Cactus" },
    { text: "&#x1F336;", id: "hot-pepper", title: "Hot Pepper" },
    { text: "&#x1F337;", id: "tulip", title: "Tulip" },
    { text: "&#x1F338;", id: "cherry-blossom", title: "Cherry Blossom" },
    { text: "&#x1F339;", id: "rose", title: "Rose" },
    { text: "&#x1F33A;", id: "hibiscus", title: "Hibiscus" },
    { text: "&#x1F33B;", id: "sunflower", title: "Sunflower" },
    { text: "&#x1F33C;", id: "blossom", title: "Blossom" },
    { text: "&#x1F33D;", id: "ear-of-maize", title: "Ear of Maize" },
    { text: "&#x1F33E;", id: "ear-of-rice", title: "Ear of Rice" },
    { text: "&#x1F33F;", id: "herb", title: "Herb" },
    { text: "&#x1F340;", id: "four-leaf-clover", title: "Four Leaf Clover" },
    { text: "&#x1F341;", id: "maple-leaf", title: "Maple Leaf" },
    { text: "&#x1F342;", id: "fallen-leaf", title: "Fallen Leaf" },
    { text: "&#x1F343;", id: "leaf-fluttering-in-wind", title: "Leaf Fluttering in Wind" },

    /* moon & sun */
    { text: "&#x1F31F;", id: "glowing-star", title: "Glowing Star" },
    { text: "&#x1F320;", id: "shooting-star", title: "Shooting Star" },
    { text: "&#x1F311;", id: "new-moon-symbol", title: "New Moon Symbol" },
    { text: "&#x1F312;", id: "waxing-crescent-moon-symbol", title: "Waxing Crescent Moon Symbol" },
    { text: "&#x1F313;", id: "first-quarter-moon-symbol", title: "First Quarter Moon Symbol" },
    { text: "&#x1F314;", id: "waxing-gibbous-moon-symbol", title: "Waxing Gibbous Moon Symbol" },
    { text: "&#x1F315;", id: "full-moon-symbol", title: "Full Moon Symbol" },
    { text: "&#x1F316;", id: "waning-gibbous-moon-symbol", title: "Waning Gibbous Moon Symbol" },
    { text: "&#x1F317;", id: "last-quarter-moon-symbol", title: "Last Quarter Moon Symbol" },
    { text: "&#x1F318;", id: "waning-crescent-moon-symbol", title: "Waning Crescent Moon Symbol" },
    { text: "&#x1F319;", id: "crescent-moon", title: "Crescent Moon" },
    { text: "&#x1F31A;", id: "new-moon-with-face", title: "New Moon with Face" },
    { text: "&#x1F31B;", id: "first-quarter-moon-with-face", title: "First Quarter Moon with Face" },
    { text: "&#x1F31C;", id: "last-quarter-moon-with-face", title: "Last Quarter Moon with Face" },
    { text: "&#x1F31D;", id: "full-moon-with-face", title: "Full Moon with Face" },
    { text: "&#x1F31E;", id: "sun-with-face", title: "Sun with Face" },
    { text: "&#x1FA90;", id: "saturn", title: "Saturn" },


    /* weather */
    { text: "&#x26C5;", id: "sun-behind-cloud", title: "Sun behind cloud" },
    { text: "&#x1f302;", id: "closed-umbrella", title: "Closed umbrella" },
     { text: "&#x1f303;", id: "night-with-stars", title: "night with stars" },
    { text: "&#x1f301;", id: "foggy", title: "Foggy" },
    { text: "&#x1f304;", id: "sunrise-over-mountains", title: "Sunrise over mountains" },
    { text: "&#x1f305;", id: "sunrise", title: "Sunrise" },
    { text: "&#x1f306;", id: "cityscape-at-dusk", title: "Cityscape at dusk" },
    { text: "&#x1f307;", id: "sunset-over-buildings", title: "Sunset over buildings" },
    { text: "&#x1f308;", id: "rainbow", title: "rainbow" },
    { text: "&#127754;", id: "water-wave", title: "Water wave" },
    { text: "&#x2600;", id: "black-sun-with-rays", title: "Black sun with rays" },
    { text: "&#x2601;", id: "cloud", title: "Cloud" },
    { text: "&#x26C4;", id: "snowman", title: "Snowman" },
/* new weather */
    { text: "&#x1F324;", id: "sun-behind-small-cloud", title: "Sun Behind Small Cloud" },
    { text: "&#x1F325;", id: "sun-behind-large-cloud", title: "Sun Behind Large Cloud" },
    { text: "&#x1F326;", id: "sun-behind-rain-cloud", title: "Sun Behind Rain Cloud" },
    { text: "&#x1F327;", id: "cloud-with-rain", title: "Cloud with Rain" },
    { text: "&#x1F328;", id: "cloud-with-snow", title: "Cloud with Snow" },
    { text: "&#x1F329;", id: "cloud-with-lightning-and-rain", title: "Cloud with Lightning and Rain" },
    { text: "&#x1F32A;", id: "cloud-with-lightning", title: "Cloud with Lightning" },
    { text: "&#x1F32B;", id: "tornado", title: "Tornado" },
    { text: "&#x1F32C;", id: "fog", title: "Fog" },
    { text: "&#x1F300;", id: "cyclone", title: "Cyclone" },
    { text: "&#x1F308;", id: "rainbow", title: "Rainbow" },
    { text: "&#x1F302;", id: "closed-umbrella", title: "Closed Umbrella" },
    { text: "&#x1F303;", id: "umbrella", title: "Umbrella" },
    { text: "&#x1F304;", id: "umbrella-with-rain-drops", title: "Umbrella with Rain Drops" },
    { text: "&#x1F305;", id: "high-voltage", title: "High Voltage" },
    { text: "&#x1F306;", id: "snowflake", title: "Snowflake" },
    { text: "&#x1F307;", id: "snowman", title: "Snowman" },
    { text: "&#x1F309;", id: "comet", title: "Comet" },


    /* others*/
    { text: "&#x1F384;", id: "christmas-tree", title: "Christmas Tree" },
    { text: "&#x1F386;", id: "fireworks", title: "Fireworks" },
    { text: "&#x1F387;", id: "firework-sparkler", title: "Firework Sparkler" },
    { text: "&#x1F9E8;", id: "yarn", title: "Yarn" },
    { text: "&#128293;", id: "fire", title: "Fire" },
    { text: "&#x1F388;", id: "balloon", title: "Balloon" },
    { text: "&#x1F389;", id: "party-popper", title: "Party Popper" },
    { text: "&#x1F38A;", id: "confetti-ball", title: "Confetti Ball" },
    { text: "&#x1F38B;", id: "tanabata-tree", title: "Tanabata Tree" },
    { text: "&#x1F38D;", id: "pine-decoration", title: "Pine Decoration" },
    { text: "&#x1F38E;", id: "japanese-dolls", title: "Japanese Dolls" },
    { text: "&#x1F38F;", id: "carp-streamer", title: "Carp Streamer" },
    { text: "&#x1F390;", id: "wind-chime", title: "Wind Chime" },
    { text: "&#x2660;", id: "black-spade-suit", title: "Black spade suit" },
    { text: "&#x2663;", id: "black-club-suit", title: "Black club suit" },
    { text: "&#x2665;", id: "black-heart-suit", title: "Black heart suit" },
    { text: "&#x2666;", id: "black-diamond-suit", title: "Black diamond suit" },
    { text: "&#x2648;", id: "aries", title: "Aries" },
    { text: "&#x2649;", id: "taurus", title: "Taurus" },
    { text: "&#x264a;", id: "gemini", title: "gemini" },
    { text: "&#x264b;", id: "cancer", title: "Cancer" },
    { text: "&#x264c;", id: "leo", title: "Leo" },
    { text: "&#x264d;", id: "virgo", title: "virgo" },
    { text: "&#x264e;", id: "libra", title: "Libra" },
    { text: "&#x264f;", id: "scorpius", title: "Scorpius" },
    { text: "&#x2650;", id: "sagittarius", title: "Sagittarius" },
    { text: "&#x2651;", id: "capricorn", title: "Capricorn" },
    { text: "&#x2652;", id: "aquarius", title: "Aquarius" },
    { text: "&#x2653;", id: "pisces", title: "Pisces" },
    { text: "&#x26ce;", id: "ophiuchus", title: "ophiuchus" },
    { text: "&#x1f500;", id: "twisted-rightwards-arrows", title: "Twisted rightwards arrows" },
    { text: "&#x1f501;", id: "clockwise-rightwards-and-leftwards-open-circle-arrows", title: "Clockwise rightwards and leftwards open circle arrows" },
    { text: "&#x1f502;", id: "clockwise-rightwards-and-leftwards-open-circle-arrows-with-circled-one-overlay", title: "Clockwise rightwards and leftwards open circle arrows with circled one overlay" },
    { text: "&#x1f503;", id: "clockwise-downwards-and-upwards-open-circle-arrows", title: "Clockwise downwards and upwards open circle arrows" },
    { text: "&#x1f504;", id: "anticlockwise-downwards-and-upwards-open-circle-arrows", title: "Anticlockwise downwards and upwards open circle arrows" },

    /* transportes */
    { text: "&#x1F680;", id: "rocket", title: "Rocket" },
    { text: "&#x1F681;", id: "helicopter", title: "Helicopter" },
    { text: "&#x1F682;", id: "steam-locomotive", title: "Steam Locomotive" },
    { text: "&#x1F683;", id: "railway-car", title: "Railway Car" },
    { text: "&#x1F684;", id: "bullet-train", title: "Bullet Train" },
    { text: "&#x1F685;", id: "train", title: "Train" },
    { text: "&#x1F686;", id: "high-speed-train", title: "High-Speed Train" },
    { text: "&#x1F687;", id: "high-speed-train-with-bullet-nose", title: "High-Speed Train with Bullet Nose" },
    { text: "&#x1F688;", id: "light-rail", title: "Light Rail" },
    { text: "&#x1F689;", id: "metro", title: "Metro" },
    { text: "&#x1F68A;", id: "station", title: "Station" },
    { text: "&#x1F68B;", id: "tram", title: "Tram" },
    { text: "&#x1F68C;", id: "tram-car", title: "Tram Car" },
    { text: "&#x1F68D;", id: "bus", title: "Bus" },
    { text: "&#x1F68E;", id: "oncoming-bus", title: "Oncoming Bus" },
    { text: "&#x1F68F;", id: "trolleybus", title: "Trolleybus" },
    { text: "&#x1F690;", id: "bus-stop", title: "Bus Stop" },
    { text: "&#x1F691;", id: "minibus", title: "Minibus" },
    { text: "&#x1F692;", id: "ambulance", title: "Ambulance" },
    { text: "&#x1F693;", id: "fire-engine", title: "Fire Engine" },
    { text: "&#x1F694;", id: "police-car", title: "Police Car" },
    { text: "&#x1F695;", id: "oncoming-police-car", title: "Oncoming Police Car" },
    { text: "&#x1F696;", id: "taxi", title: "Taxi" },
    { text: "&#x1F697;", id: "oncoming-taxi", title: "Oncoming Taxi" },
    { text: "&#x1F698;", id: "automobile", title: "Automobile" },
    { text: "&#x1F699;", id: "oncoming-automobile", title: "Oncoming Automobile" },
    { text: "&#x1F69A;", id: "recreational-vehicle", title: "Recreational Vehicle" },
    { text: "&#x1F69B;", id: "delivery-truck", title: "Delivery Truck" },
    { text: "&#x1F69C;", id: "articulated-lorry", title: "Articulated Lorry" },
    { text: "&#x1F69D;", id: "tractor", title: "Tractor" },
    { text: "&#x1F69E;", id: "monorail", title: "Monorail" },
    { text: "&#x1F69F;", id: "mountain-railway", title: "Mountain Railway" },
    { text: "&#x1F6A0;", id: "suspension-railway", title: "Suspension Railway" },
    { text: "&#x1F6A1;", id: "mountain-cableway", title: "Mountain Cableway" },
    { text: "&#x1F9BD;", id: "manual-wheelchair", title: "Manual Wheelchair" },
    { text: "&#x1F9BE;", id: "motorized-wheelchair", title: "Motorized Wheelchair" },
    { text: "&#x1F6F5;", id: "motor-scooter", title: "Motor Scooter" },
    { text: "&#x1F6F4;", id: "kick-scooter", title: "Kick Scooter" },
    { text: "&#x1F6B2;", id: "bicycle", title: "Bicycle" },
    { text: "&#x1F6F6;", id: "canoe", title: "Canoe" },
    { text: "&#x1F6F9;", id: "skateboard", title: "Skateboard" },

    /* buildings */
    { text: "&#x1F3E0;", id: "house-building", title: "House Building" },
    { text: "&#x1F3E1;", id: "house-with-garden", title: "House with Garden" },
    { text: "&#x1F3E2;", id: "office-building", title: "Office Building" },
    { text: "&#x1F3E3;", id: "japanese-post-office", title: "Japanese Post Office" },
    { text: "&#x1F3E4;", id: "post-office", title: "Post Office" },
    { text: "&#x1F3E5;", id: "hospital", title: "Hospital" },
    { text: "&#x1F3E6;", id: "bank", title: "Bank" },
    { text: "&#x1F3E7;", id: "hotel", title: "Hotel" },
    { text: "&#x1F3E8;", id: "love-hotel", title: "Love Hotel" },
    { text: "&#x1F3E9;", id: "convenience-store", title: "Convenience Store" },
    { text: "&#x1F3EA;", id: "school", title: "School" },
    { text: "&#x1F3EB;", id: "department-store", title: "Department Store" },
    { text: "&#x1F3EC;", id: "factory", title: "Factory" },
    { text: "&#x1F3ED;", id: "izakaya-lantern", title: "Izakaya Lantern" },
    { text: "&#127983;", id: "japanese-castle", title: "Japanese Castle" },
    { text: "&#127984;", id: "european-castle", title: "European Castle" }

    /* Flags
    { text: "&#x1F1E6;&#x1F1E8;", id: "flag-for-Andorra", title: "Flag for Andorra" },
    { text: "&#x1F1E6;&#x1F1E9;", id: "flag-for-United-Arab-Emirates", title: "Flag for United Arab Emirates" },
    { text: "&#x1F1E6;&#x1F1EA;", id: "flag-for-Afghanistan", title: "Flag for Afghanistan" },
    { text: "&#x1F1E6;&#x1F1EB;", id: "flag-for-Antigua-and-Barbuda", title: "Flag for Antigua and Barbuda" },
    { text: "&#x1F1E6;&#x1F1EC;", id: "flag-for-Anguilla", title: "Flag for Anguilla" },
    { text: "&#x1F1E6;&#x1F1EE;", id: "flag-for-Albania", title: "Flag for Albania" },
    { text: "&#x1F1E6;&#x1F1F1;", id: "flag-for-Armenia", title: "Flag for Armenia" },
    { text: "&#x1F1E6;&#x1F1F2;", id: "flag-for-Angola", title: "Flag for Angola" },
    { text: "&#x1F1E6;&#x1F1F4;", id: "flag-for-Argentina", title: "Flag for Argentina" },
    { text: "&#x1F1E6;&#x1F1F6;", id: "flag-for-American-Samoa", title: "Flag for American Samoa" },
    { text: "&#x1F1E6;&#x1F1F7;", id: "flag-for-Austria", title: "Flag for Austria" },
    { text: "&#x1F1E6;&#x1F1F8;", id: "flag-for-Australia", title: "Flag for Australia" },
    { text: "&#x1F1E6;&#x1F1F9;", id: "flag-for-Aruba", title: "Flag for Aruba" },
    { text: "&#x1F1E6;&#x1F1FA;", id: "flag-for-Åland-Islands", title: "Flag for Åland Islands" },
    { text: "&#x1F1E6;&#x1F1FC;", id: "flag-for-Azerbaijan", title: "Flag for Azerbaijan" },
    { text: "&#x1F1E6;&#x1F1FD;", id: "flag-for-Bosnia-and-Herzegovina", title: "Flag for Bosnia and Herzegovina" },
    { text: "&#x1F1E6;&#x1F1FF;", id: "flag-for-Barbados", title: "Flag for Barbados" },
    { text: "&#x1F1E7;&#x1F1E6;", id: "flag-for-Bangladesh", title: "Flag for Bangladesh" },
    { text: "&#x1F1E7;&#x1F1E7;", id: "flag-for-Belgium", title: "Flag for Belgium" },
    { text: "&#x1F1E7;&#x1F1E9;", id: "flag-for-Burkina-Faso", title: "Flag for Burkina Faso" },
    { text: "&#x1F1E7;&#x1F1EA;", id: "flag-for-Bulgaria", title: "Flag for Bulgaria" },
    { text: "&#x1F1E7;&#x1F1EB;", id: "flag-for-Bahrain", title: "Flag for Bahrain" }
    */

    /* 
    deportes
    { text: "&#x1F3C0;", id: "basketball-and-hoop", title: "Basketball and Hoop" },
    { text: "&#x1F3C1;", id: "chequered-flag", title: "Chequered Flag" },
    { text: "&#x1F3C2;", id: "snowboarder", title: "Snowboarder" },
    { text: "&#x1F3C3;", id: "runner", title: "Runner" },
    { text: "&#x1F3C4;", id: "surfer", title: "Surfer" },
    { text: "&#x1F3C6;", id: "trophy", title: "Trophy" },
    { text: "&#x1F3C8;", id: "american-football", title: "American Football" },
    { text: "&#x1F3CA;", id: "swimmer", title: "Swimmer" },
    */


]

export default emojis;







