const smileys = [

    /* smileys */
    { text: "&#x1F600;", id: "grinning-face", title: "Grinning Face" },
    { text: "&#x1F601;", id: "grinning-face-with-smiling-eyes", title: "grinning face with smiling eyes" },
    { text: "&#x1F602;", id: "face-with-tears-of-joy", title: "Face with tears of joy" },
    { text: "&#x1F603;", id: "smiling-face-with-open-mouth", title: "Smiling face with open mouth" },
    { text: "&#x1F604;", id: "smiling-face-with-open-mouth-and-smiling-eyes", title: "Smiling face with open mouth and smiling eyes" },
    { text: "&#x1F605;", id: "smiling-face-with-open-mouth-and-cold-sweat", title: "Smiling face with open mouth and cold sweat" },
    { text: "&#x1F606;", id: "smiling-face-with-open-mouth-and-tightly-closed-eyes", title: "Smiling face with open mouth and tightly-closed eyes" },
    { text: "&#x1F607;", id: "smiling-face-with-halo", title: "Smiling face with halo" },
    { text: "&#x1F608;", id: "smiling-face-with-horns", title: "Smiling face with horns" },
    { text: "&#x1F609;", id: "winking-face", title: "winking face" },
    { text: "&#x1F60A;", id: "smiling-face-with-smiling-eyes", title: "Smiling face with smiling eyes" },
    { text: "&#x1F60B;", id: "face-savouring-delicious-food", title: "Face savouring delicious food" },
    { text: "&#x1F60C;", id: "relieved-face", title: "relieved face" },
    { text: "&#x1F60D;", id: "smiling-face-with-heart-shaped-eyes", title: "Smiling face with heart-shaped eyes" },
    { text: "&#x1F60E;", id: "smiling-face-with-sunglasses", title: "Smiling face with sunglasses" },
    { text: "&#x1F60F;", id: "smirking-face", title: "Smirking face" },
    { text: "&#x1F610;", id: "neutral-face", title: "neutral face" },
    { text: "&#x1F611;", id: "expressionless-face", title: "expressionless face" },
    { text: "&#x1F612;", id: "unamused-face", title: "unamused face" },
    { text: "&#x1F613;", id: "face-with-cold-sweat", title: "Face with cold sweat" },
    { text: "&#x1F614;", id: "pensive-face", title: "Pensive face" },
    { text: "&#x1F615;", id: "confused-face", title: "Confused face" },
    { text: "&#x1F616;", id: "confounded-face", title: "Confounded face" },
    { text: "&#x1F617;", id: "kissing-face", title: "kissing face" },
    { text: "&#x1F618;", id: "face-throwing-a-kiss", title: "Face throwing a kiss" },
    { text: "&#x1F619;", id: "kissing-face-with-smiling-eyes", title: "kissing face with smiling eyes" },
    { text: "&#x1F61A;", id: "kissing-face-with-closed-eyes", title: "kissing face with closed eyes" },
    { text: "&#x1F61B;", id: "face-with-stuck-out-tongue", title: "Face with stuck-out tongue" },
    { text: "&#x1F61C;", id: "face-with-stuck-out-tongue-and-winking-eye", title: "Face with stuck-out tongue and winking eye" },
    { text: "&#x1F61D;", id: "face-with-stuck-out-tongue-and-tightly-closed-eyes", title: "Face with stuck-out tongue and tightly-closed eyes" },
    { text: "&#x1F61E;", id: "disappointed-face", title: "Disappointed face" },
    { text: "&#x1F61F;", id: "worried-face", title: "worried face" },
    { text: "&#x1F620;", id: "angry-face", title: "Angry face" },
    { text: "&#x1F621;", id: "pouting-face", title: "Pouting face" },
    { text: "&#x1F622;", id: "crying-face", title: "Crying face" },
    { text: "&#x1F623;", id: "persevering-face", title: "Persevering face" },
    { text: "&#x1F624;", id: "face-with-look-of-triumph", title: "Face with look of triumph" },
    { text: "&#x1F625;", id: "disappointed-but-relieved-face", title: "Disappointed but relieved face" },
    { text: "&#x1F626;", id: "frowning-face-with-open-mouth", title: "Frowning face with open mouth" },
    { text: "&#x1F627;", id: "anguished-face", title: "Anguished face" },
    { text: "&#x1F628;", id: "fearful-face", title: "Fearful face" },
    { text: "&#x1F629;", id: "weary-face", title: "weary face" },
    { text: "&#x1F62A;", id: "sleepy-face", title: "Sleepy face" },
    { text: "&#x1F62B;", id: "tired-face", title: "Tired face" },
    { text: "&#x1F62C;", id: "grimacing-face", title: "grimacing face" },
    { text: "&#x1F62D;", id: "loudly-crying-face", title: "Loudly crying face" },
    { text: "&#x1F62E;", id: "face-with-open-mouth", title: "Face with open mouth" },
    { text: "&#x1F62F;", id: "hushed-face", title: "Hushed face" },
    { text: "&#x1F630;", id: "face-with-open-mouth-and-cold-sweat", title: "Face with open mouth and cold sweat" },
    { text: "&#x1F631;", id: "face-screaming-in-fear", title: "Face screaming in fear" },
    { text: "&#x1F632;", id: "astonished-face", title: "Astonished face" },
    { text: "&#x1F633;", id: "flushed-face", title: "Flushed face" },
    { text: "&#x1F634;", id: "sleeping-face", title: "Sleeping face" },
    { text: "&#x1F635;", id: "dizzy-face", title: "Dizzy face" },
    { text: "&#x1F636;", id: "face-without-mouth", title: "Face without mouth" },
    { text: "&#x1F637;", id: "face-with-medical-mask", title: "Face with medical mask" },
    { text: "&#x1F641;", id: "slightly-frowning-face", title: "Slightly frowning face" },
    { text: "&#x1F642;", id: "slightly-smiling-face", title: "Slightly smiling face" },
    { text: "&#x1F643;", id: "upside-down-face", title: "upside-down face" },
    { text: "&#x1F644;", id: "face-with-rolling-eyes", title: "Face with rolling eyes" },
    { text: "&#x1F910;", id: "zipper-mouth-face", title: "zipper-mouth face" },
    { text: "&#x1F911;", id: "money-mouth-face", title: "Money-mouth face" },
    { text: "&#x1F912;", id: "face-with-thermometer", title: "Face with thermometer" },
    { text: "&#x1F913;", id: "nerd-face", title: "nerd face" },
    { text: "&#x1F914;", id: "thinking-face", title: "Thinking face" },
    { text: "&#x1F915;", id: "face-with-head-bandage", title: "Face with head-bandage" },
    { text: "&#x1f920;", id: "face-with-cowboy-hat", title: "Face with cowboy hat" },
    { text: "&#x1f921;", id: "clown-face", title: "Clown face" },
    { text: "&#x1f922;", id: "nauseated-face", title: "nauseated face" },
    { text: "&#x1f923;", id: "rolling-on-the-floor-laughing", title: "rolling on the floor laughing" },
    { text: "&#x1f924;", id: "drooling-face", title: "Drooling face" },
    { text: "&#x1f925;", id: "lying-face", title: "Lying face" },
    { text: "&#x1f927;", id: "shushing-face", title: "Shushing face" },
    { text: "&#x1f928;", id: "face-with-hand-over-mouth", title: "Face with hand over mouth" },
    { text: "&#x1f929;", id: "grinning-face-with-star-eyes", title: "grinning face with star eyes" },
    { text: "&#x1f92a;", id: "grinning-face-with-one-large-and-one-small-eye", title: "grinning face with one large and one small eye" },
    { text: "&#x1f92b;", id: "face-with-finger-covering-closed-lips", title: "Face with finger covering closed lips" },
    { text: "&#x1f92c;", id: "serious-face-with-symbols-covering-mouth", title: "Serious face with symbols covering mouth" },
    { text: "&#x1f92d;", id: "smiling-face-with-smiling-eyes-and-hand-covering-mouth", title: "Smiling face with smiling eyes and hand covering mouth" },
    { text: "&#x1f92e;", id: "face-with-open-mouth-vomiting", title: "Face with open mouth vomiting" },
    { text: "&#x1f92f;", id: "shocked-face-with-exploding-head", title: "Shocked face with exploding head" },
    { text: "&#x1f9d0;", id: "face-with-monocle", title: "Face with monocle" },
    { text: "&#x1F4A9;", id: "pile-of-poo", title: "Pile of poo" },
    { text: "&#x1F638;", id: "grinning-cat-face-with-smiling-eyes", title: "grinning cat face with smiling eyes" },
    { text: "&#x1F639;", id: "cat-face-with-tears-of-joy", title: "cat face with tears of joy" },
    { text: "&#x1F63A;", id: "smiling-cat-face-with-open-mouth", title: "smiling cat face with open mouth" },
    { text: "&#x1F63B;", id: "smiling-cat-face-with-heart-shaped-eyes", title: "smiling cat face with heart-shaped eyes" },
    { text: "&#x1F63C;", id: "cat-face-with-wry-smile", title: "cat face with wry smile" },
    { text: "&#x1F63D;", id: "kissing-cat-face-with-closed-eyes", title: "kissing cat face with closed eyes" },
    { text: "&#x1F63E;", id: "pouting-cat-face", title: "pouting cat face" },
    { text: "&#x1F63F;", id: "crying-cat-face", title: "crying cat face" },
    { text: "&#x1F640;", id: "weary-cat-face", title: "weary cat face" },
    { text: "&#x1F648;", id: "see-no-evil-monkey", title: "see-no-evil monkey" },
    { text: "&#x1F649;", id: "hear-no-evil-monkey", title: "hear-no-evil monkey" },
    { text: "&#x1F64A;", id: "speak-no-evil-monkey", title: "speak-no-evil monkey" },


]

export default smileys;







